### ISSUE TITLE
when the browser get a json request, Chinese characters are not displayed properly

### ISSUE THREAD

**Issue by piaohao** [actframework/actframework#100]
the controller method :
```java
json(Object);
```
request in the browser:
![image](https://cloud.githubusercontent.com/assets/2724549/23990021/a87400ee-0a6f-11e7-9eef-8b5612f055fe.png)
we can see, the chinese characters are not displayerd properly, but it is right in the chrome develop tools.

I contrast it with jfinal request, 
jfinal response header is : 
![image](https://cloud.githubusercontent.com/assets/2724549/23990143/0f89d31c-0a70-11e7-838b-b2c60efe210e.png)

act response header is:
![image](https://cloud.githubusercontent.com/assets/2724549/23990162/2191bb56-0a70-11e7-87a2-d7f900e7a408.png)

**Comment by greenlaw110** [comment]
@piaohao I did some research I found these info:

As per http://www.ietf.org/rfc/rfc7159.txt
![image](https://cloud.githubusercontent.com/assets/216930/24015367/6b9b6c4e-0adc-11e7-8020-39802f859413.png)

As per https://www.techempower.com/benchmarks/#section=code
![image](https://cloud.githubusercontent.com/assets/216930/24015410/812e1f7a-0adc-11e7-9759-0e0dd4470e23.png)

**Comment by greenlaw110** [comment]
Now with act-1.0.3-SNAPSHOT, you just need to add the following line in your app configuration file:

```
render.json.output_charset=false
```

It will output charset in your JSON response `Content-Type` header

**Comment by piaohao** [comment]
got it

**Comment by piaohao** [comment]
hello,green,i found this bug not completely fixed.
int the 1.0.3 snapshot, the Chinese character displayed properly whern the browser request a json firtst time , but when you refresh the browser, the next requests were not right, Chinese characters were still not right.

**Comment by greenlaw110** [comment]
@piaohao are you able to see the `charset=UTF-8` in the Content-Type header (in response)?

**Comment by piaohao** [comment]
yes
