### ISSUE TITLE
Calling mailer method asynchronously by eventBus.trigger didn't work

### ISSUE THREAD

**Issue by DannyChen88** [actframework/actframework#1009]
Calling mailer method asynchronously by eventBus.trigger didn't work. console showed nothing. the program are as follows.
![image](https://user-images.githubusercontent.com/4637194/49562222-81cc8200-f955-11e8-93d0-78336a700052.png)

![image](https://user-images.githubusercontent.com/4637194/49562244-9f015080-f955-11e8-8746-87f31e901ed0.png)

**Comment by greenlaw110** [comment]
There are two problems identified:

1. If the simple event handler method arguments has List typed argument in the list it will fail
2. If any `null` value passed in the `EventBus.trigger` method, it will fail silently.

For the first issue, we can work out by mapping implementation of List type to the `List.class`.  while for the second issue, we should raise `NullPointerException` in such case
