### ISSUE TITLE
IE doesn't support "application/json" content type

### ISSUE THREAD

**Issue by rickycoder** [actframework/actframework#101]
http://actframework.org/doc/templating.md

IE will start to download the data if it set response `Content-Type` to `application/json`

**Comment by greenlaw110** [comment]
If your app need to support IE and is vulnerable to the IE `application/json` issue, then add the following line to your app configuration file:

```
render.json.content_type.ie=text/plain
```

Other than `text/plain`, you can also choose to use `text/html`, `text/x-json` or `text/javascript` based on your app usage.

See 

* http://www.entwicklungsgedanken.de/2008/06/06/problems-with-internet-explorer-and-applicationjson/
* http://stackoverflow.com/questions/13943439/json-response-download-in-ie710
