### ISSUE TITLE
Using @Cron("0 0 2 * * ?") job to send email, job executed once but received email at 1:59 and 13:59

### ISSUE THREAD

**Issue by DannyChen88** [actframework/actframework#1020]
job log just wrote once at 1:59,  but i received emails at 1:59 and 13:59 respectively.

**Comment by CrossLee** [comment]
![image](https://user-images.githubusercontent.com/4584905/49920741-477b5b80-fee6-11e8-9c05-7f5401ed37ce.png)

**Comment by greenlaw110** [comment]
@CrossLee is the issue still there?

**Comment by CrossLee** [comment]
@greenlaw110 现在没有了。
