### ISSUE TITLE
HTTP Status 500 - Servlet execution threw an exception 

### ISSUE THREAD

**Issue by ArieiiV** [actframework/actframework#1023]
I keep getting this error , i don't know how to solve it...... can anyone help me? It always happens when i'm trying to invoke my servlet after click the button  "save" on my form....
I found some people saying that maybe the jar file is not on classpath, but all my jars are on the classpath, if anyone here still thinking about the classpath, please let me know the name of such jar file i should put in this project.....

> This is my web.xml
`     <?xml version="1.0" encoding="UTF-8"?>
    <web-app version="3.1" xmlns="http://xmlns.jcp.org/xml/ns/javaee" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web- 
    app_3_1.xsd">
    <servlet>
        <servlet-name>CanalClienteControle</servlet-name>
        <servlet-class>br.com.sky.iTvMC.controler.CanalClienteControle</servlet-class>
    </servlet>
   
    <servlet-mapping>
        <servlet-name>CanalClienteControle</servlet-name>
        <url-pattern>/CanalClienteControle</url-pattern>
    </servlet-mapping>
   
    <session-config>
        <session-timeout>30</session-timeout>
     </session-config>
      <welcome-file-list>
  	<welcome-file>index.html</welcome-file>
  	<welcome-file>index.htm</welcome-file>
    </welcome-file-list>
    </web-app>
`

> This is my persistence.xml

`     <persistence version="2.1"
	xmlns="http://xmlns.jcp.org/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema- 
      instance"
	xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence 
    http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">

	<persistence-unit name="bancoItv">
		<provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>

		<class>br.com.sky.iTvMC.modelo.ApplicationItv</class> 
		<class>br.com.sky.iTvMC.modelo.AppointmentCategory</class> 
		<class>br.com.sky.iTvMC.modelo.Bit</class> 
		<class>br.com.sky.iTvMC.modelo.Cartelas</class> 
		<class>br.com.sky.iTvMC.modelo.Channel</class> 
		<class>br.com.sky.iTvMC.modelo.ChannelCategory</class>
		<class>br.com.sky.iTvMC.modelo.City</class> 
		<class>br.com.sky.iTvMC.modelo.ClientChannel</class> 
		<class>br.com.sky.iTvMC.modelo.ClientChannelAppointment</class> 
		<class>br.com.sky.iTvMC.modelo.Image</class> 
		<class>br.com.sky.iTvMC.modelo.ImageCategory</class>
		<class>br.com.sky.iTvMC.modelo.Segmentation</class> 
		<class>br.com.sky.iTvMC.modelo.SegmentationRules</class> 
		<class>br.com.sky.iTvMC.modelo.Video</class> 
		<class>br.com.sky.iTvMC.modelo.VideoArtist</class> 
		<class>br.com.sky.iTvMC.modelo.VideoCategory</class> 

		<properties>
			
			<property name="javax.persistence.jdbc.driver" value="oracle.jdbc.OracleDriver" />
			<property name="javax.persistence.jdbc.url" 
    value="jdbc:oracle:thin:@10.16.2.30:1423:apps" />
			<property name="javax.persistence.jdbc.user" value="adminbd" />
			<property name="javax.persistence.jdbc.password" value="bd15" />
			
			<property name="hibernate.dialect" value="org.hibernate.dialect.OracleDialect" />
			<property name="hibernate.show_sql" value="true" />
			<property name="hibernate.format_sql" value="true" />
			
			<property name="hibernate.hbm2ddl.auto" value="update" />
		</properties>
	</persistence-unit>
    </persistence>`

> This is my controler

`    package br.com.sky.iTvMC.controler;

    import java.io.IOException;

    import javax.persistence.EntityManager;
    import javax.servlet.RequestDispatcher;
    import javax.servlet.ServletException;
    import javax.servlet.http.HttpServlet;
    import javax.servlet.http.HttpServletRequest;
    import javax.servlet.http.HttpServletResponse;

    import br.com.sky.iTvMC.modelo.*;
    import br.com.sky.iTvMC.util.BDUtil;
    import br.com.sky.iTvMC.util.JPAUtil;
    import br.com.sky.iTvMC.dao.CartelasDao;

    public class CanalClienteControle extends HttpServlet {

	private static final long serialVersionUID = 1L;
	String ret;

	protected void processRequest(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		response.setContentType("text/html;charset=UTF-8");

		String oAcao = request.getParameter("salvarCartela2");
		if (oAcao.contains("cartela2_incluir")) {
		System.out.println("1 ---------------------------");

			try {
				System.out.println("2  -------------------");
				EntityManager manager = new JPAUtil().getEntityManager();
				
				
				System.out.println("3 -------------------");
				CartelasDao dao = new CartelasDao(manager);
				Cartelas cartelas = new Cartelas();
				
				
				cartelas.setCelula(Integer.parseInt(request.getParameter("option")));
				cartelas.setInitial_date(request.getParameter("inicioCartela2"));
				cartelas.setFinal_date(request.getParameter("fimCartela2"));
				cartelas.setNameimg(request.getParameter("nomeCartela2"));
				cartelas.setServer_folder(request.getParameter("C:\\"));
				cartelas.setWho(request.getParameter("Karoline Viana"));
				
                

				manager.getTransaction().begin();
				dao.add(cartelas);
				manager.getTransaction().commit();
				manager.close();
				System.out.println("4 -------------------");
				
			} catch (NumberFormatException e) {
				 ret = "Problema ao tentar incluir (camada CONTROLLER): " + e.getMessage();
	             request.setAttribute("mensagem", ret);
				BDUtil bdUtil = new BDUtil();
				bdUtil.trataSQLException(e);
				System.out.println("5 -------------------");
			}
			RequestDispatcher redireciona = request.getRequestDispatcher("mensagem.jsp");
			redireciona.forward(request, response);
		}
	}

	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		processRequest(request, response);
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		processRequest(request, response);
	}

    }
`

> This is my class 

`    package br.com.sky.iTvMC.modelo;

    import javax.persistence.Entity;
    import javax.persistence.GeneratedValue;
    import javax.persistence.GenerationType;
    import javax.persistence.Id;
    import javax.persistence.SequenceGenerator;
    import javax.persistence.Table;

    @Table(name = "CARTELAS_NEW_CHANNEL_HD")
    @Entity
    public class Cartelas {
	@SequenceGenerator(name = "seqCart", sequenceName = "SEQ_CARTELAS_NEW_CHANNEL_HD", 
    allocationSize = 1)
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seqCart")
	private Integer id;
	private String nameimg;
	private String server_folder;
	private String initial_date;
	private String final_date;
	private Integer celula;
	private String who;
	
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getNameimg() {
		return nameimg;
	}
	public void setNameimg(String nameimg) {
		this.nameimg = nameimg;
	}
	public String getServer_folder() {
		return server_folder;
	}
	public void setServer_folder(String server_folder) {
		this.server_folder = server_folder;
	}
	public String getInitial_date() {
		return initial_date;
	}
	public void setInitial_date(String initial_date) {
		this.initial_date = initial_date;
	}
	public String getFinal_date() {
		return final_date;
	}
	public void setFinal_date(String final_date) {
		this.final_date = final_date;
	}
	public Integer getCelula() {
		return celula;
	}
	public void setCelula(Integer celula) {
		this.celula = celula;
	}
	public String getWho() {
		return who;
	}
	public void setWho(String who) {
		this.who = who;
	}
	
	
	
    }
`

> This is my class DAO
`    package br.com.sky.iTvMC.dao;

    import java.util.List;

    import javax.persistence.EntityManager;

    import br.com.sky.iTvMC.modelo.Cartelas;

    public class CartelasDao {
	private EntityManager manager;
	
	public CartelasDao(EntityManager manager) {
		this.manager = manager;
	}

	public void add(Cartelas clientChannel) {
		this.manager.persist(clientChannel);
	}

	public void remove(Cartelas clientChannel) {
		this.manager.remove(clientChannel);
	}
	
	public void update(Cartelas clientChannel) {
		this.manager.merge(clientChannel);
	}

	public Cartelas find(Integer id) {
		return this.manager.find(Cartelas.class, id);
	}

	public List<Cartelas> list() {
		return this.manager.createQuery("SELECT * FROM CARTELAS_NEW_CHANNEL_HD", 
    Cartelas.class).getResultList();
	}
    }
`

> This is the error 

HTTP Status 500 - Servlet execution threw an exception type Exception report

message Servlet execution threw an exception

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Servlet execution threw an exception org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) root cause

java.lang.NoClassDefFoundError: javax/persistence/Persistence br.com.sky.iTvMC.util.JPAUtil.(JPAUtil.java:9) br.com.sky.iTvMC.controler.CanalClienteControle.processRequest(CanalClienteControle.java:37) br.com.sky.iTvMC.controler.CanalClienteControle.doPost(CanalClienteControle.java:79) javax.servlet.http.HttpServlet.service(HttpServlet.java:648) javax.servlet.http.HttpServlet.service(HttpServlet.java:729) org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) root cause

java.lang.ClassNotFoundException: javax.persistence.Persistence org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1332) org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1166) br.com.sky.iTvMC.util.JPAUtil.(JPAUtil.java:9) br.com.sky.iTvMC.controler.CanalClienteControle.processRequest(CanalClienteControle.java:37) br.com.sky.iTvMC.controler.CanalClienteControle.doPost(CanalClienteControle.java:79) javax.servlet.http.HttpServlet.service(HttpServlet.java:648) javax.servlet.http.HttpServlet.service(HttpServlet.java:729) org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) note The full stack trace of the root cause is available in the Apache Tomcat/8.0.36 logs.

**Comment by greenlaw110** [comment]
@ArieiiV are you using ActFramework? Act does not support Servlet and it does not require Tomcat to run

**Comment by greenlaw110** [comment]
@ArieiiV I am closing this issue as it is invalid to ActFramework. If you are looking for answers to specific Servlet/Tomcat issue, try [Stackoverflow](https://stackoverflow.com/questions/ask)
