### ISSUE TITLE
ObjectID not return String when renderJSON 

### ISSUE THREAD

**Issue by dreamingo88** [actframework/actframework#1029]
it will return like this::::

"id": {
     "machineIdentifier": 1463868,
     "processIdentifier": 24104,
     "counter": 5242188,
     "timestamp": 1545126548
}

**Comment by dreamingo88** [comment]
Steps with CRUD::::
1. POST http://localhost:5460/api/v1/content
insert some mongodb documents;

2. POST http://localhost:5460/api/v1/content/show/5c19eec016563c4c3cf72227   (ID)
objectid will return like above.

but, if use GET http://localhost:5460/api/v1/content/show/5c19eec016563c4c3cf72227
it works right (return string).

**Comment by greenlaw110** [comment]
@dreamingo88 is this issue still valid?

**Comment by dreamingo88** [comment]
It works right now.

**Comment by greenlaw110** [comment]
good. thanks
