### ISSUE TITLE
Morphia ObjectId not generate in api-book

### ISSUE THREAD

**Issue by dreamingo88** [actframework/actframework#1033]
Test with crud:::
http://ip:5460/~/api#POSTBookmarkService_show

 Return value sample:::
{
	"st":1,
	"status":0,
	"title":"mc2YJ@",
	"url":"https://desjardiws.com.au/...",
	"viewTimes":0
}

**Comment by greenlaw110** [comment]
This is an invalid issue. The reason `id` is not generated is because your `ModelMorphiaX` has been declared as `@NoBind`:

![image](https://user-images.githubusercontent.com/216930/50362055-3ef7e480-05ba-11e9-96b0-6f62dd674e72.png)

**Comment by greenlaw110** [comment]
Actually I give it a second thought, the return sample shall actually contains NoBind fields while param sample shall strip off the fields that are not eligible to binding.
