### ISSUE TITLE
Could act only open a new port when the configuration api_doc=true

### ISSUE THREAD

**Issue by leeaee** [actframework/actframework#1056]
I noticed there is an new port 5463 opened when act started. 
And this port is usually for API DOC. Sometime in PROD environment, the API DOC is not enabled, but the port is still be token by ACT.
Could ACT only open the new port when the configuration api_doc=true?

**Comment by greenlaw110** [comment]
It can't disable 5463 just because of API is not enabled. 5463 is a system port, it also support `/~/info` and `/~/conf` end points at PROD mode
