### ISSUE TITLE
Simplify the use of `@url` and `@fullUrl` tag

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#108]
At the moment if we want to use `@url` or `@fullUrl` tag to do reverse route lookup we must specify the full action path. E.g. if we can a route mapping as:

```
GET /foo/bar com.my.company.prod_x.controller.FooController.bar
```

And we want to do the reverse route look up in our rythm template we must specify the full action path

```
<a href='@url("com.my.company.prod_x.controller.FooController.bar")'>Foo bar</a>
```

This request is about simplified the usage of `@url` and `@fullUrl` so that we pass the short path for the action like:

```
@// case 1
<a href='@url(bar())'>Foo bar</a>
```

or 

```
@// case 2
<a href='@url(TheOtherController.index)'>Go to the other service</a>
```

## How to infer the full action path

<a name="infer_reference"></a>
### 1. Identify the reference action path

If the template corresponding to an action handler, e.g. `/pkg/MyController/index.html` corresponding to   `pkg.MyController.index`, any invoke of `@url` or `@fullUrl` inside the `/pkg/MyController/index.html`, it shall refer to `pkg.MyController` when infering the full action path

If there is no mapping action handler for this template, i.e. this is free template, then it shall check the current context method path and use it as the reference action path. If there is no concurrent context, then it is a invalid call to find out the reference action path

### 2. Infer full action path from reference action path

Example A

|       field                |   value                                  |
| ----------------------- |  ------------------------------------ |
| reference action path  |  `com.my.company.prod_x.controller.MyController.login` |
| supplied action path | `home`  |
| inferred full path | `com.my.company.prod_x.controller.MyController.home` |

Example B

|       field                |   value                                  |
| ----------------------- |  ------------------------------------ |
| reference action path  |  `com.my.company.prod_x.controller.LoginController.login` |
| supplied action path | `MyController.home`  |
| inferred full path | `com.my.company.prod_x.controller.MyController.home` |

Example C

|       field                |   value                                  |
| ----------------------- |  ------------------------------------ |
| reference action path  |  `com.my.company.prod_x.controller.LoginController.login` |
| supplied action path | `service.MyService.home`  |
| inferred full path | `service.MyService.home` |

In Example C, there is no way to infer the full path, thus it returns the passed path directly

**Comment by mezongzi** [comment]
好的，谢谢啦
