### ISSUE TITLE
建议增强osgl#getMethod()的实现

### ISSUE THREAD

**Issue by moonmanbu** [actframework/actframework#1092]
当前实现为
```java
    public static Method getMethod(Class c, String methodName, Class... argTypes) {
        try {
            return c.getMethod(methodName, argTypes);
        } catch (NoSuchMethodException e) {
            return null;
        }
    }
```
直接调用的Class#getMethod()方法, 不能获取object的所有Method, 建议按照fosgl#fieldsOf()的实现方法重新实现

**Comment by moonmanbu** [comment]
> 当前实现为
> 
> ```java
>     public static Method getMethod(Class c, String methodName, Class... argTypes) {
>         try {
>             return c.getMethod(methodName, argTypes);
>         } catch (NoSuchMethodException e) {
>             return null;
>         }
>     }
> ```
> 
> 直接调用的Class#getMethod()方法, 不能获取object的所有Method, 建议按照fosgl#fieldsOf()的实现方法重新实现

**Comment by greenlaw110** [comment]
Please raise this issue to osglworks/java-tool project
