### ISSUE TITLE
setPropertySpec cann't work with inner object

### ISSUE THREAD

**Issue by dreamingo88** [actframework/actframework#1101]
1. update crud module to lastest;
2. config common/db.properties (db.pwd) ;
3. run crud, add some record to mysql;
4. POST http://localhost:5460/api/v1/content/show/123456
{
	"d": {
		"fields": "id,title,content,inner,v"
	}
}
result: inner.parent is null.
if comment setPropertySpec, it works right.

**Comment by greenlaw110** [comment]
You need to specify `inner.parent` explicitly:
![image](https://user-images.githubusercontent.com/216930/55475620-22ab1f80-5660-11e9-9b77-55bb716e146f.png)

**Comment by dreamingo88** [comment]
OK, it works now.

**Comment by dreamingo88** [comment]
But the config is complex.
Can it work with "fields": "id,title,content,inner,v"?

**Comment by greenlaw110** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/216930/56364590-42cb0900-6232-11e9-8f8a-8ffd51d38f12.png)
