### ISSUE TITLE
Mock data function for development

### ISSUE THREAD

**Issue by leeaee** [actframework/actframework#1106]
@greenlaw110 Front development is depend on backend api. Sometimes api development is always slow, so the front developer is waiting when backend api developing. Could act provide a function that act can provide mock data function: when the REST api interface is defined, it could return mock data easily, so that front and backend development can work together.

**Comment by greenlaw110** [comment]
Done! Here is how to mock your API:

Suppose your have an API endpoint that returns an employee data by id, you can declare the endpoint and throw out a `ToBeImplemented` exception via `E.tbd()` call:

```java
    /**
     * Returns an employee by id
     * @param id the email of the employee to be returned
     * @return an employee
     */
    @GetAction("{id}")
    public Employee getEmployee(String id) {
        throw E.tbd();
    }
```

When app start in DEV mode, the framework will intercept the `ToBeImplemented` exception and generate mock data:

![image](https://user-images.githubusercontent.com/216930/55550338-b396ff00-5723-11e9-8604-8e5d40bbab37.png)
