### ISSUE TITLE
new to ACT Framework

### ISSUE THREAD

**Issue by raj4java** [actframework/actframework#1107]
I like Act framework but we are also using Postgressql as our main and only DB. I am also interested in an example on how to use similar to  java AAA approach as mentioned in this post with Permisions Roles, Subjects groups, prinicpals etc.

Some documentation, tutorial or the pgsql schema would be nice to have

Many thanks in advance
Raja

**Comment by greenlaw110** [comment]
Hi @raj4java 

Thank you for your interesting to ActFramework. At the moment I am eagerly working on 1.8.20 release. I will come up with a demo app that load AAA objects from SQL database (could be pgsql or mysql or any database with jdbc support).

I am closing this issue as it duplicates to #1094

**Comment by greenlaw110** [comment]
@raj4java here is the sample project:
https://github.com/act-gallery/bookmark
