### ISSUE TITLE
Configurable URL router support

### ISSUE THREAD

**Issue by leeaee** [actframework/actframework#1116]
Now, we defined the url router like @UrlContext("/api/v1")
sometimes, we need to update the version just like v1 -> v2.
Could act support configurable url router so that we can modified the version number in properties file.

**Comment by greenlaw110** [comment]
Now it can do something like:

```java
@UrlContext("api/${api.version}")
public class ServiceBase {}
```
In the configuration file, add `api.version` :

```
api.version=1
```
