### ISSUE TITLE
H.Rquest.fullUrl() shall not output `80` when sending to port `80`

### ISSUE THREAD

**Issue by piaohao** [actframework/actframework#114]
when I request like this: "http://piaohao.org/info", in the backend , request.fullUrl() is "http://piaohao.org:80/info", actually, the program don't want to get this result, while "http://piaohao.org/info" is the right one.

**Comment by greenlaw110** [comment]
moved to https://github.com/osglworks/java-http/issues/1

**Comment by greenlaw110** [comment]
Fixed in osgl-http-1.0.1

**Comment by piaohao** [comment]
ok
