### ISSUE TITLE
Running `mvn clean package -Pdocker` Error

### ISSUE THREAD

**Issue by donald2150** [actframework/actframework#1150]
```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.24.0:build (build) on project toilet: Execution build of goal io.fabric8:docker-maven-plugin:0.24.0:build failed: Given Docker name '/placeholder:1.0-SNAPSHOT-b7192' is invalid:
[ERROR]    * user part '' doesn't match allowed pattern '[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?'
[ERROR] See http://bit.ly/docker_image_fmt for more details
```

**Comment by greenlaw110** [comment]
@donald2150 please add the following line into the `properties` section of your `pom.xml` file:

```
<docker.repo>${project.groupId}/${project.artifactId}</docker.repo>
```

**Comment by greenlaw110** [comment]
Before fixing:
![gh1150-before](https://user-images.githubusercontent.com/216930/59956255-a55eb080-94d2-11e9-8ffb-e5751b162762.gif)

After fixing:
![gh1150-after](https://user-images.githubusercontent.com/216930/59956259-ab549180-94d2-11e9-8441-57d39205fb89.gif)

**Comment by greenlaw110** [comment]
After fixing:
![gh1150-after](https://user-images.githubusercontent.com/216930/59956259-ab549180-94d2-11e9-8441-57d39205fb89.gif)
