### ISSUE TITLE
UrlContext not working in all Action

### ISSUE THREAD

**Issue by xkcoding** [actframework/actframework#1174]
demo code fragment

```java
package com.xkcoding.demo.action;

import act.controller.annotation.UrlContext;
import cn.hutool.core.lang.Dict;
import cn.hutool.json.JSONUtil;
import me.zhyd.oauth.config.AuthSource;
import org.osgl.http.H;
import org.osgl.mvc.annotation.GetAction;

/**
 * <p>
 * 第三方登录请求处理
 * </p>
 *
 * @author yangkai.shen
 * @date Created in 2019-07-22 18:30
 */
@UrlContext("/oauth")
@SuppressWarnings("unused")
public class OAuthAction {

    /**
     * 登录类型
     */
    @GetAction
    public void loginType(H.Response response) {
        response.writeText("no path variable");
    }

    @GetAction("/login/{source}")
    public void login(String source, H.Response response) {
        response.writeText(source);
    }
}
```

Act version: 1.8.26.0

app.properties
```properties
http.port=8080
url.context=/demo
```

This demo URL :
http://localhost:8080/demo/oauth
http://localhost:8080/demo/login/qq

expect URL：
http://localhost:8080/demo/oauth
http://localhost:8080/demo/oauth/login/qq

**Comment by oshatrk** [comment]
@xkcoding Your route should be relative (without first `/`):
`@GetAction("login/{source}")`

**Comment by greenlaw110** [comment]
Thanks @oshatrk you are right 

@xkcoding please let us know if the problem has been fixed after changing URL path to relative.

**Comment by xkcoding** [comment]
Thanks @oshatrk and it's working!

@greenlaw110 I finished a demo about Act how to intergration with JustAuth, https://github.com/xkcoding/act-justauth-demo

[JustAuth](https://github.com/zhangyd-c/JustAuth) is easier to intergration third part of social login~

**Comment by greenlaw110** [comment]
Thanks @xkcoding ! 

Actually I can invite you to join me on https://github.com/actframework/act-social-link development? Basically I want to add social integration for QQ, wechat, weibo etc.

**Comment by xkcoding** [comment]
I need to learn about act plugin development first ~ 😄

**Comment by greenlaw110** [comment]
@xkcoding I don't think there is too much to learn for you to step in. The sociallink project has all the plumbings setup, and armed with google, facebook, github, linkedin already. It's not that hard to get more social providers plug into the existing system.
