### ISSUE TITLE
Ehcache not working in Act since 1.8.27

### ISSUE THREAD

**Issue by IceCream-Open** [actframework/actframework#1220]
在新版本中注入EhcacheService，EhcacheService 实例内 cache 对象为 null，无法正常使用。
在Act 1.8.27版本开始出现的本问题。

**Comment by greenlaw110** [comment]
Issue can be reproduced:

![image](https://user-images.githubusercontent.com/216930/67193937-e4c9e900-f441-11e9-8dec-53191f7d990b.png)
