### ISSUE TITLE
Annotition @NoAuthentication Can't be work with annotition: @with(BeetlSqlTransactional.class)

### ISSUE THREAD

**Issue by babogd** [actframework/actframework#1231]
ACT-AAA使用的确比SpringSecurity要轻便的多，各种认证方式也比较简单，但在最近使用中遇到一个问题：当注释@NoAuthentication与@With(BeetlSqlTransactional.class)同时在class上使用时，@NoAuthentication将不起作用，所注class下的请求方法，不登陆均报401 未认证的错误。
请及时修正。
至于是不是与其他注释同时使用也会出现此问题，还未验证。。。

**Comment by greenlaw110** [comment]
@babogd 这个问题是由于 Authentication 在 BeetlSqlTransactional 上面的 Intercepter 还存在引起的. 我需要想想怎么解决这个问题.

**Comment by greenlaw110** [comment]
@babogd 你在 `src/main/resources` 下面加上一个文件: `aaa.authenticate.list`, 其中放入下面的内容:

```
-act.db.beetlsql.BeetlSqlTransactional
```

看看能不能解决你的问题

**Comment by greenlaw110** [comment]
This should be fixed by https://github.com/actframework/act-beetlsql/issues/17
