### ISSUE TITLE
ApiDoc bug: JPA Entity field 

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#1259]
![WX20191211-152845](https://user-images.githubusercontent.com/9036838/70600623-1b92d300-1c2b-11ea-947f-5317efa81538.png)

MySQL Database is not support new Date() String value.
log out on act/apidoc/Endpoint.java:981

is on  act/apidoc/Endpoint.java:813?
![image](https://user-images.githubusercontent.com/9036838/70600810-a1af1980-1c2b-11ea-924b-9cf51373d91b.png)

**Comment by greenlaw110** [comment]
This is caused by https://github.com/osglworks/java-tool/issues/224
