### ISSUE TITLE
静态资源访问出错

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#1281]
在routes.conf配置文件配置如下：
GET /static resource:static 时，我用angular build工具打包的angular项目放到该定义路由下面的文件夹时，部分文件无法访问。出现404问题，目测是文件名太长吧。
换成 #GET /mgr file:classes/admin 方式定义就可以，但是这样的缺点是上产模式和开发模式路径不一致，而且直接访问目录路径不会自动索引index.html，还需要在地址栏加index.html才能访问到静态页面。

**Comment by greenlaw110** [comment]
superseded by #1283
