### ISSUE TITLE
Act start error during plugin scan, not supported jre version class load

### ISSUE THREAD

**Issue by Burtsev-Alexey** [actframework/actframework#1288]
Stacktrace:

```
Caused by: java.lang.UnsupportedClassVersionError: [classname] has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at act.boot.BootstrapClassLoader.defineClassX(BootstrapClassLoader.java:96)
	at act.boot.BootstrapClassLoader.defineClass(BootstrapClassLoader.java:104)
	at act.boot.app.FullStackAppBootstrapClassLoader.loadActClass(FullStackAppBootstrapClassLoader.java:411)
	at act.boot.app.FullStackAppBootstrapClassLoader.loadClass(FullStackAppBootstrapClassLoader.java:375)
	at act.boot.app.FullStackAppBootstrapClassLoader.pluginClasses(FullStackAppBootstrapClassLoader.java:110)
	at act.Act.pluginClasses(Act.java:266)
	at act.plugin.PluginScanner.scan(PluginScanner.java:45)
	at act.Act.loadPlugins(Act.java:1003)
	at act.Act.startup(Act.java:332)
	at act.Act.startup(Act.java:1282)
```

**Comment by greenlaw110** [comment]
@Burtsev-Alexey 
It looks like some of your jar file is built on Java9, however your JRE is Java 8.

**Comment by Burtsev-Alexey** [comment]
Its not my jar that contains Java9 compiled classes. I'm including Cassandra Java driver, looks like it contains mixed java8 java9 classes. I haven't used Java9 yet, but I guess you can build Java9 jars that can contain both java8 and java9 classes and run appropriate code depending on JRE.

The problem is very easy to reproduce.
Create minimal pom with 2 dependencies: ACT and Cassandra.
`    <dependencies>
        <dependency>
            <groupId>org.actframework</groupId>
            <artifactId>act</artifactId>
            <version>1.8.30a</version>
        </dependency>
        <dependency>
            <groupId>com.datastax.oss</groupId>
            <artifactId>java-driver-core</artifactId>
            <version>4.3.1</version>
        </dependency>
    </dependencies>
`
And create main function:
`
    public static void main(String[] args) throws Exception {
        Act.start();
    }
`
You will get an exception about module.info class.
Unfortunately it doesn't tell what jar contained it. But after some research a colleague of my suggested that it's 'jackson-' dependency.

**Comment by Burtsev-Alexey** [comment]
We have used maven-enforcer-plugin with:
```
<rules>
   <enforceBytecodeVersion>
     <maxJdkVersion>1.8</maxJdkVersion>
```

The output is:
Restricted to JDK 1.8 yet org.ow2.asm:asm-tree:jar:7.1:compile contains module-info.class targeted to JDK 1.9
Restricted to JDK 1.8 yet com.fasterxml.jackson.core:jackson-annotations:jar:2.10.0:compile contains module-info.class targeted to JDK 1.9
Restricted to JDK 1.8 yet com.fasterxml.jackson.core:jackson-core:jar:2.10.0:compile contains module-info.class targeted to JDK 1.9
Restricted to JDK 1.8 yet org.ow2.asm:asm:jar:7.1:compile contains module-info.class targeted to JDK 1.9
Restricted to JDK 1.8 yet com.fasterxml.jackson.core:jackson-databind:jar:2.10.0:compile contains module-info.class targeted to JDK 1.9
Restricted to JDK 1.8 yet org.ow2.asm:asm-commons:jar:7.1:compile contains module-info.class targeted to JDK 1.9
Restricted to JDK 1.8 yet org.ow2.asm:asm-util:jar:7.1:compile contains module-info.class targeted to JDK 1.9
Restricted to JDK 1.8 yet org.ow2.asm:asm-analysis:jar:7.1:compile contains module-info.class targeted to JDK 1.9

**Comment by greenlaw110** [comment]
@Burtsev-Alexey java-driver-core-4.2.2 version is able to run on JDK 8

**Comment by Burtsev-Alexey** [comment]
> @Burtsev-Alexey java-driver-core-4.2.2 version is able to run on JDK 8

Yes it is. the problem is not with 'java-driver-core' the problem is 'jackson' library that is used in it. It has support for Java >=8 modular architecture by including module-info.class.

As a quick fix i have done this: `System.setProperty("act.jar.app.ignore", "jackson-");`

But you should probably consider that there will be increasingly more java libraries that has support for Java >=9 modular architecture containing module-info.class compiled with java > 8.

ACT should probably have default ignore setting to not load module-info.class from jars.

**Comment by greenlaw110** [comment]
@Burtsev-Alexey 
Thanks for the information. Yes I am considering support modern Java runtime in Act 2 (which probably will come out later this year).

**Comment by greenlaw110** [comment]
Added jackson into default black list file: `act.jar.black.list`
