### ISSUE TITLE
setting act.db.ebean.EbeanPlugin   Appear -create-all.sql

### ISSUE THREAD

**Issue by mezongzi** [actframework/actframework#129]
setting act.db.ebean.EbeanPlugin   Appear -create-all.sql
![image](https://cloud.githubusercontent.com/assets/7627445/24533566/4819da42-15fb-11e7-9ec0-2e36d680c404.png)

**Comment by greenlaw110** [comment]
this one should have been fixed already. @mezongzi can you please verify it on the 1.3.0 version?
