### ISSUE TITLE
Beetl模板中的自定义函数没有自动注册

### ISSUE THREAD

**Issue by BoboYaya** [actframework/actframework#1315]
自定义函数代码
```
import org.beetl.core.Context;
import org.beetl.core.Function;
import org.osgl.util.S;

import javax.inject.Named;

public class BeetlTestFunction implements Function {

    @Named("myFunc")
    @Override
    public Object call(Object[] objects, Context context) {
        String value = (String) objects[0];
        String ovalue = (String) objects[1];
        if(S.eq(value, ovalue, S.IGNORECASE)){
            return "checked";
        }
        return "";
    }
}
```

报错：该方法未注册(FUNCTION_NOT_FOUND)

**Comment by greenlaw110** [comment]
@BoboYaya 
Problem is your `@Named` annotation should be put at the class level, instead of `call` function level, try this:

```java
import org.beetl.core.Context;
import org.beetl.core.Function;
import org.osgl.util.S;

import javax.inject.Named;

@Named("myFunc") // `@Named` annotation should be put in here!
public class BeetlTestFunction implements Function {

    @Override
    public Object call(Object[] objects, Context context) {
        String value = (String) objects[0];
        String ovalue = (String) objects[1];
        if(S.eq(value, ovalue, S.IGNORECASE)){
            return "checked";
        }
        return "";
    }
}
```

**Comment by BoboYaya** [comment]
Great job! Thanks!!



At 2020-03-17 03:49:15, "Green Luo" <notifications@github.com> wrote:

@BoboYaya
Problem is your @Named annotation should be put at the class level, instead of call function level, try this:

importorg.beetl.core.Context;
importorg.beetl.core.Function;
importorg.osgl.util.S;

importjavax.inject.Named;

@Named("myFunc") // `@Named` annotation should be put in here!publicclassBeetlTestFunctionimplementsFunction {

    @OverridepublicObjectcall(Object[] objects, Contextcontext) {
        String value = (String) objects[0];
        String ovalue = (String) objects[1];
        if(S.eq(value, ovalue, S.IGNORECASE)){
            return"checked";
        }
        return"";
    }
}
