### ISSUE TITLE
CLI over HTTP - allow specify big string which require textarea as input

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1321]
![image](https://user-images.githubusercontent.com/216930/77842597-f4631000-71df-11ea-9c84-e35d62c44a05.png)

Proposed solution:

* Add Annotation `@MultiLines`
* In case a parameter is marked as `@MultiLines` the CLI over http template shall render the input using `<textarea>

**Comment by CINJ** [comment]
This needs to be enforced over https

**Comment by greenlaw110** [comment]
@CINJ this is only a DEV mode feature. It is not available on the default HTTP port when app is running in PROD mode.
