### ISSUE TITLE
Support customised resource bundle encoding

### ISSUE THREAD

**Issue by andnnl** [actframework/actframework#1329]
At the moment ACT read resource file (properties file) with default `ISO-8859-1` encoding when running on Java before Java 9.

This CR is to allow it support other file encoding, e.g. `UTF-8` to load property files when running Act on Java 8.

As an example, spring support specify resource encoding using the following configuration:

```
spring.messages.encoding=UTF-8
```

**Comment by greenlaw110** [comment]
Fixed. It supports adding the following configurations to specify the resource bundle encoding:

```
resource_bundle.encoding=utf-8
```
