### ISSUE TITLE
时不时报错，net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#1343]
某些接口json返回报错，某些时候不报错。一般是SPA单页页面进入时候报错
![image](https://user-images.githubusercontent.com/9036838/85937775-521b0b80-b939-11ea-8b6b-a8a07bec088d.png)
![image](https://user-images.githubusercontent.com/9036838/85937820-99a19780-b939-11ea-8624-a33b1273e755.png)
![image](https://user-images.githubusercontent.com/9036838/85937823-a32aff80-b939-11ea-90e6-a8f4aee591a9.png)
如果数据库修改返回条数为10就没任何报错，但是我现在返回的数据条数也就100多条就报错了。

**Comment by greenlaw110** [comment]
@jiankian 能发下你的控制器和请求响应方法吗?

**Comment by greenlaw110** [comment]
另外请报告一下你的 Act 版本

**Comment by fh2002** [comment]
不要直接返回json,用json.toString()，参考下issues    1350

**Comment by greenlaw110** [comment]
Close as no response from issue reporter. If you still have the issue, please raise an new one.
