### ISSUE TITLE
内置部署支持

### ISSUE THREAD

**Issue by pmmcc** [actframework/actframework#1349]
1. 访问指定路径实现自动部署
2. 具有ip白名单功能
   如果配置了白名单,应该只允许白名单中的ip可以部署
   如果没有任何配置默认允许开发环境和测试环境的部署,
   任何情况下不允许uat环境和生产环境的部署.
   如果白名单配置为局域网(一个约定的字符串),仅允许局域网中的ip可以部署
3. 可以在配置文件中指定部署的shell脚本的位置
4. 待部署的代码应该由部署服务器从git服务器下载,
   而不是由开发者上传编译后的文件到部署服务器.
5. 配置文件配置的git账号密码应该可以加密.

**Comment by jiankian** [comment]
写个脚本不就行了
