### ISSUE TITLE
java.lang.LinkageError

### ISSUE THREAD

**Issue by sminnu** [actframework/actframework#1351]
I am getting this exception while running my unit-test. How to solve this?

```
loader constraint violation: when resolving method "javax.xml.parsers.DocumentBuilder.parse(Ljava/io/InputStream;)Lorg/w3c/dom/Document;" the class loader (instance of org/powermock/core/classloader/MockClassLoader) of the current class, com/amazonaws/util/XpathUtils, and the class loader (instance of <bootloader>) for the method's defining class, javax/xml/parsers/DocumentBuilder, have different Class objects for the type org/w3c/dom/Document used in the signature
java.lang.LinkageError: loader constraint violation: when resolving method "javax.xml.parsers.DocumentBuilder.parse(Ljava/io/InputStream;)Lorg/w3c/dom/Document;" the class loader (instance of org/powermock/core/classloader/MockClassLoader) of the current class, com/amazonaws/util/XpathUtils, and the class loader (instance of <bootloader>) for the method's defining class, javax/xml/parsers/DocumentBuilder, have different Class objects for the type org/w3c/dom/Document used in the signature
	at com.amazonaws.util.XpathUtils.documentFrom(XpathUtils.java:180)
```

**Comment by greenlaw110** [comment]
@sminnu looks like a class loader caused conflict. I haven't been through this issue before. Can you please share your pom dependencies? Or let me know which version of powermock you are using.

**Comment by sminnu** [comment]
@greenlaw110 
Powermock version: 'powermock-core', version: '1.6.6'

I am using Gradle
`configurations {
    compile.exclude module: 'aws-java-sdk-api-gateway'
    compile.exclude module: 'aws-java-sdk-sns'
    compile.exclude module: 'aws-java-sdk-sts'
    compile.exclude module: 'aws-java-sdk-ec2'
    compile.exclude module: 'aws-java-sdk-iam'
    compile.exclude module: 'aws-java-sdk'
    compile.exclude module: 'aws-java-sdk-iam'
    compile.exclude module: 'aws-java-sdk-sts'

    compile.exclude module: 'bcprov-jdk15on'

}

dependencies {
    compile group: 'com.typesafe', name: 'config', version:'1.3.1'
    compile group: 'com.bazaarvoice.jolt', name: 'jolt-core', version:'0.1.0'
    compile group: 'com.bazaarvoice.jolt', name: 'json-utils', version:'0.1.0'
    compile group: 'junit', name: 'junit', version:'4.12'
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version:'2.7.3'
    compile group: 'org.xerial.snappy', name: 'snappy-java', version:'1.1.2.6'
    compile group: 'org.apache.commons', name: 'commons-io', version: '1.3.2'
    compile group: 'net.logstash.log4j', name: 'jsonevent-layout',version : '1.7'
    compile group: 'com.jayway.jsonpath', name: 'json-path', version: '2.2.0'
    compile group: 'io.searchbox', name: 'jest', version: '2.4.0'
    compile group: 'org.codehaus.groovy', name: 'groovy-json', version: '2.5.0-alpha-1'
    compile 'org.json:json:20160810'
    compile 'org.codehaus.jackson:jackson-mapper-asl:1.9.12'
    compile 'commons-collections:commons-collections:3.2.2'
    compile group: 'com.joestelmach', name: 'natty', version: '0.12'
    compile group: 'com.microsoft.sqlserver', name: 'mssql-jdbc', version: '6.2.1.jre8'
    compile group: 'com.amazonaws', name: 'aws-java-sdk-lambda', version: '1.11.248'
    compile group: 'com.amazonaws', name: 'aws-java-sdk-cloudwatch', version: '1.11.819'
    compile group: 'com.amazonaws', name: 'aws-java-sdk-kinesis', version: '1.11.260'
    compile group: 'com.amazonaws', name: 'aws-java-sdk-rds', version: '1.11.810'
    compile project(':em-dl-core')
    compile group: 'org.codehaus.jackson', name: 'jackson-mapper-asl', version: '1.9.12'
    compile group: 'com.flipkart.zjsonpatch', name: 'zjsonpatch', version: '0.4.4'
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version:'2.7.3'
    // https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp
    compile group: 'com.squareup.okhttp3', name: 'okhttp', version: '3.10.0'
    compile group: 'com.fasterxml.jackson.dataformat', name: 'jackson-dataformat-cbor', version: '2.8.10'
    compile group: 'com.google.guava', name: 'guava', version: '26.0-jre'

    compile 'org.elasticsearch.client:elasticsearch-rest-client:5.6.3'
    compile 'org.elasticsearch.client:elasticsearch-rest-high-level-client:5.6.3'

    testCompile group: 'org.elasticsearch', name: 'elasticsearch', version:'2.3.2'

    // https://mvnrepository.com/artifact/com.google.code.gson/gson
    compile group: 'com.google.code.gson', name: 'gson', version: '2.7'


    testCompile group: 'org.easymock', name: 'easymock', version: '3.4'
    testCompile group: 'org.powermock', name: 'powermock-core', version: '1.6.6'
    testCompile group: 'org.powermock', name: 'powermock-module-junit4', version: '1.6.6'
    testCompile group: 'org.powermock', name: 'powermock-api-easymock', version: '1.6.6'
    testCompile group: 'junit', name: 'junit', version:'4.12'
    testCompile group: 'org.mockito', name: 'mockito-all', version: '1.10.19'
    testCompile('org.powermock:powermock-core:1.6.6')
    testCompile('org.powermock:powermock-module-junit4:1.6.6')
    testCompile('org.powermock:powermock-api-easymock:1.6.6')
    testCompile group: 'org.jmockit', name: 'jmockit', version: '1.8'
    testCompile('org.powermock:powermock-api-mockito:1.6.6')
    testCompile group: 'junit', name: 'junit', version:'4.12'
    testCompile group: 'org.mockito', name: 'mockito-all', version: '1.10.19'

    compile project(':em-dl-core')
    compile project(':em-dl-utils')
    compile project(':event-insights')
    compile project(':em-dl-loan-schema')
}`

**Comment by sminnu** [comment]
@greenlaw110  any update?

**Comment by greenlaw110** [comment]
Hi @sminnu 

I have created a sample project with the following dependencies:

```xml
    <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-core</artifactId>
      <version>1.6.6</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-api-mockito</artifactId>
      <version>1.6.6</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-module-junit4</artifactId>
      <version>1.6.6</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-all</artifactId>
      <version>1.10.19</version>
      <scope>test</scope>
    </dependency>
```

And the one unit test class:

```java
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mockito;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;
import osgl.ut.TestBase;

import static org.mockito.Mockito.when;

@RunWith(PowerMockRunner.class)
@PrepareForTest(fullyQualifiedNames = "com.fh.test.*")
public class AppEntryTest extends TestBase {

    @Test
    public void test() {
        PowerMockito.mockStatic(AppEntry.class);
        when(AppEntry.firstMethod(Mockito.anyString()))
                .thenReturn("Hello Baeldung!");
    }
}
```

I can build and package this project without problem:
![image](https://user-images.githubusercontent.com/216930/88169564-7ed3f180-cc5f-11ea-8a9f-2b6e42e7b40a.png)

I was wondering if you can share a sample project reproduce this issue to me?

**Comment by greenlaw110** [comment]
hi @sminnu how are you going? Did you have any progress on this issue?

**Comment by greenlaw110** [comment]
Close as no response from issue reporter
