### ISSUE TITLE
Allow developer to specify ECJ compiler options

### ISSUE THREAD

**Issue by IceCream-Open** [actframework/actframework#1353]
Java 14 supports [Record class](https://blogs.oracle.com/javamagazine/records-come-to-java). However this is a preview feature. We want to turn on `--enable-preview` ECJ option to allow us use Record class in Act application.

**Comment by greenlaw110** [comment]
Now it can use System properties to pass in ECJ compiler options. E.g. to turn on `--enable-preview`, use

```
-Dorg.eclipse.jdt.core.compiler.problem.enablePreviewFeatures=enabled
```

Here is the full list of ECJ compiler options:

http://www.howsoftworks.net/ecj-CompilerOptions
