### ISSUE TITLE
form enctype="multipart/form-data" caused NPE.

### ISSUE THREAD

**Issue by CrossLee** [actframework/actframework#1360]
html code:

```html
<form name="test" action="/test" method="post" enctype="multipart/form-data">
<input type="text" name="user[name]" />
<input type="submit" value="submit">
</form>
```

Upon clicking submit button, Act will throw out an NPE.

**Comment by greenlaw110** [comment]
@CrossLee can you please add the controller source code as well?

**Comment by CrossLee** [comment]
@GetAction("/test")
public void test(User user){
// ...
}

**Comment by greenlaw110** [comment]
@CrossLee is this one duplicate of #1369 ?

**Comment by greenlaw110** [comment]
I am pretty sure #1369 is a duplicate of this one, which has been fixed already. So will close this issue
