### ISSUE TITLE
Hot reload not working for Bundle Resource properties

### ISSUE THREAD

**Issue by DingouerFish** [actframework/actframework#1372]
how to reproduce:
1、IDEA+jdk15
2、git clone https://github.com/act-gallery/i18n.git
3、Edit Confiurations in IDEA ,then click IDEA's debug button to start act 
4、open http://localhost:5460，choose 简体中文 ，edit messages_zh.properties，change "i18n=国际化" to "i18n=国际化3333", refresh browser , "国际化3333" does not show in the page until I restart act then refresh the page

**Comment by greenlaw110** [comment]
@DingouerFish try act-1.9.1-SNAPSHOT, add the following dependency into your pom.xml file:

```xml
    <dependency>
      <groupId>org.actframework</groupId>
      <artifactId>act</artifactId>
      <version>1.9.1-SNAPSHOT</version>
    </dependency>
```

Let me know if it works for you, but please do not close the issue if the version fixed your problem

**Comment by DingouerFish** [comment]
> ```
> 1.9.1-SNAPSHOT
> ```

I tried, it doesn't work

**Comment by DingouerFish** [comment]
> @DingouerFish try act-1.9.1-SNAPSHOT, add the following dependency into your pom.xml file:
> 
> ```
>     <dependency>
>       <groupId>org.actframework</groupId>
>       <artifactId>act</artifactId>
>       <version>1.9.1-SNAPSHOT</version>
>     </dependency>
> ```
> 
> Let me know if it works for you, but please do not close the issue if the version fixed your problem

It works

**Comment by DingouerFish** [comment]
> @DingouerFish try act-1.9.1-SNAPSHOT, add the following dependency into your pom.xml file:
> 
> ```
>     <dependency>
>       <groupId>org.actframework</groupId>
>       <artifactId>act</artifactId>
>       <version>1.9.1-SNAPSHOT</version>
>     </dependency>
> ```
> 
> Let me know if it works for you, but please do not close the issue if the version fixed your problem

I tested again, it works for messages*.properties, but not for ValidationMessages*.properties
