### ISSUE TITLE
use H.Response.output().append(byte[]) Transfer pictures exception

### ISSUE THREAD

**Issue by kukume** [actframework/actframework#1382]
my act version is 1.9.1.10 , use H.Response.output().append(byte[]) Transfer pictures exception
![](https://img.kuku.me/images/2021/03/03/IchJJ.png)
![](https://img.kuku.me/images/2021/03/03/Iclt9.png)

**Comment by greenlaw110** [comment]
@kukume 

`resp.output()` is a low level API, not intended for app developer use. Thus instead of doing this:

![image](https://user-images.githubusercontent.com/216930/111862976-c9536c80-89ac-11eb-9edd-22ec619e4ace.png)

Do this:

![image](https://user-images.githubusercontent.com/216930/111863326-1cc6ba00-89af-11eb-99dd-ffe1f795c0dd.png)

**Comment by greenlaw110** [comment]
In this latest 1.9.2-SNAPSHOT, you have three more options:

Option 1:

```java
    @PostAction
    @ResponseContentType(mediaType = H.MediaType.PNG)
    public byte[] renderImage(ISObject file) {
        return (file.asByteArray());
    }
```

Option 2:

```java
    @PostAction
    public byte[] renderImage(ISObject file, ActionContext context) {
        context.accept(H.Format.PNG);
        return (file.asByteArray());
    }
```

Option 3:

```java
    @PostAction
    public byte[] renderImage(ISObject file, H.Response<?> resp) {
        resp.contentType("image/png");
        return (file.asByteArray());
    }
```

**Comment by kukume** [comment]
How to upgrade to 1.9.2-SNAPSHOT

**Comment by greenlaw110** [comment]
@kukume 

In your `pom.xml` file add the following dependency:

```
    <dependency>
      <groupId>org.actframework</groupId>
      <artifactId>act</artifactId>
      <version>1.9.2-SNAPSHOT</version>
    </dependency>
```

**Comment by kukume** [comment]
Thanks!
