### ISSUE TITLE
How to update Xms and Xmx of the delivery by configuration or environnement variables

### ISSUE THREAD

**Issue by ahmedcdamrani** [actframework/actframework#1389]
When launching the server, I noticed the following error: "java.lang.OutOfMemoryError: Java heap space".
I would like to modify the Xmx parameters. However, it is automatically generated in the dist.
Is there any way to update these parameters by configuration or by environment variable?

**Comment by greenlaw110** [comment]
Add the following property definitions in your `pom.xml` file:

```xml
    <vmargs.heap.init>?forXms?</vmargs.heap.init>
    <vmargs.heap.max>?forXmx?</vmargs.heap.max>
```

**Comment by ahmedcdamrani** [comment]
Thank you for the answer !
