### ISSUE TITLE
url.context not show in e404 page

### ISSUE THREAD

**Issue by benstonezhang** [actframework/actframework#1391]
proposed solution is make act.route.Router.ensureUrlContext as public, then path the path string in e404 template.

patch attached.

[act_urlcontext_patch.txt](https://github.com/actframework/actframework/files/6447417/act_urlcontext_patch.txt)

**Comment by greenlaw110** [comment]
Hey @benstonezhang thanks for reporting the issue and offering the patch, can you please submit a PR so that I can give you the credential?

**Comment by benstonezhang** [comment]
As your wish, sir :-p
