### ISSUE TITLE
Rythm模板引擎渲染HTML文档首次速度太慢

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#1405]
实用Act默认的Rythm模板引擎渲染HTML页面非常难用，主要是第一次渲染或者修改了模板的代码看效果就非常慢。
就算是打包的版本，服务器上跑第一次访问页面非常慢，当然第一次访问以后第二次倒是不影响，但是在开发阶段，我每次修改HTML模板内容，就需要很长的时间才能打开页面。这个时间长达需要好几分钟都有，取决于HTML模板文件的行数，区区几行的HTML模板页面，改了立马就可以看效果，而HTML模板文件是几千行，首次打开或者修改以后页面渲染出网页需要超长时间。
bug复现项目在下方仓库，里面有两个模板文件。一个是一千多行，一个几十行以内。即便HTML模板内没有使用任何模板变量，index.html渲染速度和thin比非常明显。
![image](https://user-images.githubusercontent.com/9036838/131265266-4c24e5fd-5e7e-47e3-9aa9-918d7908c75c.png)

[https://gitee.com/jiankian/act-view-example](https://gitee.com/jiankian/act-view-example)

**Comment by greenlaw110** [comment]
This is rythm issue and there is a workaround for it: https://github.com/rythmengine/rythmengine/issues/367
