### ISSUE TITLE
Act-beetl for使用问题求助

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#1406]
演示代码如下图，使用其它模板引擎都是正常的，就是beetl不正常，for遍历数据不能访问子属性，是我语法写错了吗？找不到对应文档了。
![image](https://user-images.githubusercontent.com/9036838/132129496-91366a79-89a0-496c-aa69-11e4f6b5bf06.png)
完整代码演示仓库：
[https://gitee.com/jiankian/act-view-example](https://gitee.com/jiankian/act-view-example)

**Comment by greenlaw110** [comment]
@jiankian 你有向 beetl 项目求助吗？这个感觉和 Act 没有太大关系啊
