### ISSUE TITLE
@Before priority   BUG

### ISSUE THREAD

**Issue by kukume** [actframework/actframework#1407]
@Before注解中，其中priority属性默认为0。
我这里有2个@Before注解，其中一个没有填写priority属性，其中一个填写了priority属性，填写了priority属性（无论为何值）的before方法会慢于没有填写priority属性的before方法，
![image](https://user-images.githubusercontent.com/45278810/136161955-fb387868-713c-42e1-ac10-2c6521f6830f.png)
如图所示，其中没有填写priority属性的before方法为null，填写了的为填写的值，但是为null的before方法总是会在填写了priority属性的before方法之前执行
按照@Before注解，没有填写priority属性默认值应为0

**Comment by greenlaw110** [comment]
@kukume 

Can you try `1.9.2-SNAPSHOT` ?

**Comment by kukume** [comment]
没有问题了。
