### ISSUE TITLE
关于Action方法参数接收的疑问

### ISSUE THREAD

**Issue by kukume** [actframework/actframework#1411]
@greenlaw110 大佬
我在@Before中使用ActionContext.renderArg()方法，注入了一个对象，例如为UserEntity，
然后我可以在Action方法中的参数写上UserEntity userEntity，act会帮我自动注入这个对象。
但是在写上UserEntity后，我有一个请求，参数为{"a": "b", "b": "c"}，我新建了一个pojo对象
```java
class Test {
private String a;
private String b;
}
```
于是，我尝试在Action方法的参数中写上Test test,UserEntity userEntity，其中userEntity是被正常注入的，test为null。
当我在Action方法的参数只写Test test的时候，是能映射请求参数的。
所以请问，我可以在Action方法的参数中同时接受这2个值吗？如果可以，应该怎么操作

**Comment by greenlaw110** [comment]
@kukume when you have `UserEntity userEntity` in the argument list, there is no way for Act to infer the data to `myPojo`; you must have `myPojo` prefix to let Act know the data is for `myPojo` parameter. Hence:
![image](https://user-images.githubusercontent.com/216930/139574593-38fbe223-14f7-413a-9717-33b1afc2f944.png)

**Comment by kukume** [comment]
ok
