### ISSUE TITLE
Act 返回自己创建的图片验证码，怎么增加Session？

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#1412]
![image](https://user-images.githubusercontent.com/9036838/139727077-057955bc-81d5-4830-8560-22e0b884d4ee.png)
实现了自定义的图片验证码，但是请求此地址不能保存Session，看了下响应头没有Cookie信息。

而Spring Boot一样的方式返回验证码是有Session的
![image](https://user-images.githubusercontent.com/9036838/139727232-3cf32f42-ef81-466e-a997-cb7e2a1a08c7.png)

**Comment by greenlaw110** [comment]
@jiankian I think it is most probably because you write directly into the response output stream and ActFramework has no chance to output the session info. 

As a workaround can you try follow https://github.com/act-gallery/captcha-demo
