### ISSUE TITLE
Act框架如何配置多域名共享相同的session状态

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#1413]
我用不同的子域名来访问同一个Act服务，根据访问域名来返回不同网页，但需要登录状态等信息共享，不知道如何配置，谢谢

**Comment by greenlaw110** [comment]
不同的子域名浏览器根本不允许 session/cookie 共享。登录状态共享倒是可以通过 [单点登录](https://developer.aliyun.com/article/636281) 来实现
