### ISSUE TITLE
act.log日志如何配置成按照日期进行切割，自定义保存位置呢

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#1416]
默认情况下，act.log日志如何配置成按照日期进行切割，自定义保存位置呢？
目前默认是在项目目录下act.log文件保存，且不会切割

**Comment by greenlaw110** [comment]
You should do all log configuration via editing `/resources/logback.xml` file.

**Comment by jiankian** [comment]
> You should do all log configuration via editing `/resources/logback.xml` file.

`/resources/logback.xml` 配置了如下日志配置，但是在IDEA开发模式正常切割日志，打包上传到服务器运行依然是在项目目录下生成了一个act.log单个日志文件，请问如何处理呢？是不是配置错误呢

`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <statusListener class="ch.qos.logback.core.status.NopStatusListener"/>

    
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        
        <withJansi>true</withJansi>
        <encoder>
            <pattern>%date %highlight(%-5level) %cyan(%logger{5}@[%-4.30thread]) - %msg%n</pattern>
        </encoder>
    </appender>
    
    
    
    
    
    

    
    
    
    
    

    
    
    
    
    <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
            <FileNamePattern>log/act.log.%d{yyyy-MM-dd}.%i.log</FileNamePattern>
            <MaxHistory>3650</MaxHistory>
            <maxFileSize>10MB</maxFileSize>
        </rollingPolicy>
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="METRIC_FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
            <FileNamePattern>log/act.metric.log.%d{yyyy-MM-dd}.%i.log</FileNamePattern>
            <MaxHistory>3650</MaxHistory>
            <maxFileSize>10MB</maxFileSize>
        </rollingPolicy>
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <Pattern>%d{yyyy-MM-dd_HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</Pattern>
        </encoder>

        <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
            <FileNamePattern>/jcg.%i.log.zip</FileNamePattern>
            <MinIndex>1</MinIndex>
            <MaxIndex>10</MaxIndex>
        </rollingPolicy>

        <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
            <MaxFileSize>2MB</MaxFileSize>
        </triggeringPolicy>
    </appender>

    <logger name="act" level="INFO" additivity="false">
        <appender-ref ref="FILE"/>
        <appender-ref ref="STDOUT"/>
    </logger>

    <logger name="act.db" level="DEBUG" additivity="false">
        <appender-ref ref="FILE"/>
    </logger>

    <logger name="act.ws" level="DEBUG" additivity="false">
        <appender-ref ref="FILE"/>
        <appender-ref ref="STDOUT"/>
    </logger>

    <logger name="act.mail" level="DEBUG" additivity="false">
        <appender-ref ref="FILE"/>
    </logger>

    <logger name="metric.act" level="TRACE">
        <appender-ref ref="METRIC_FILE"/>
    </logger>

    <logger name="demo.helloworld" level="DEBUG" additivity="false">
        <appender-ref ref="FILE"/>
        <appender-ref ref="STDOUT"/>
    </logger>
    
    <logger name="ann" level="DEBUG" additivity="false">
        <appender-ref ref="FILE"/>
        <appender-ref ref="STDOUT"/>
    </logger>

    
    <logger name="io.ebean.DDL" level="TRACE"/>
    <logger name="io.ebean.SQL" level="DEBUG"/>
    <logger name="io.ebean.TXN" level="TRACE"/>
    <logger name="io.ebean.SUM" level="TRACE"/>
    
    <logger name="io.ebean.cache.QUERY" level="TRACE"/>
    <logger name="io.ebean.cache.BEAN" level="TRACE"/>
    <logger name="io.ebean.cache.COLL" level="TRACE"/>
    <logger name="io.ebean.cache.NATKEY" level="TRACE"/>
    
    <logger name="io.ebean.docker" level="TRACE"/>
    
    <logger name="io.ebean.ELA" level="TRACE"/>
    <logger name="io.ebean.ELQ" level="TRACE"/>
    <logger name="io.ebean.BULK" level="TRACE"/>

    
    <root level="DEBUG">
        <appender-ref ref="FILE"/>
        <appender-ref ref="STDOUT"/>
    </root>

</configuration>
`
