### ISSUE TITLE
Mongodb字段为对象时, 通过@PutAction无法修改

### ISSUE THREAD

**Issue by moonmanbu** [actframework/actframework#184]
public class User extends MorphiaAdaptiveRecord<User> {
    public String name;
    public String email;
    public Address address;
...
        @PutAction("/user/{id}")
        public User update(String id, Map<String, Object> properties) {
            User user = findById(id);
            notFoundIfNull(user);
            user.putValues(properties);
            save(user);
            return user;
        }
...
}

可以将前台请求映射到properties, 但是user.putValues(properties)之后, 无法映射到user对应的字段!

**Comment by greenlaw110** [comment]
duplicate issue with #193
