### ISSUE TITLE
Request to support versioning of static resource mappings

### ISSUE THREAD

**Issue by xiwasong** [actframework/actframework#210]
Reference resources:

* [https://my.oschina.net/xiwa/blog/903927](https://my.oschina.net/xiwa/blog/903927)
* [spring-mvc-static-content](http://docs.spring.io/spring-boot/docs/1.5.3.RELEASE/reference/htmlsingle/#boot-features-spring-mvc-static-content)

**Comment by mezongzi** [comment]
good

**Comment by greenlaw110** [comment]
Added support in Rythm view. Give the following code:

```
@resource("conf/app.properties")
@asset("favicon.png?n=3")
@asset("foo/bar") #non exists resource
@resource("x/dd") #non exist resource
```

It will generate something like at PROD mode:

```
/conf/app.properties?checksum=ea2550ca9302a72096365d7a48883554e02c5fe5
/asset/favicon.png?n=3&checksum=595fdf00a210712a8643e34f99c9d95b48083f92
/asset/foo/bar
/x/dd
```

where checksum is calculated from the resource content. For non-existing resource no checksum is generated.

And at DEV mode:

```
conf/app.properties?ts=1511465779934
asset/favicon.png?n=3&ts=1511465779934
asset/foo/bar?ts=1511465779934
x/dd?ts=1511465779934
```

Where `ts` is the current timestamp when generating the link.
