### ISSUE TITLE
CSRF 中 formField build 报错

### ISSUE THREAD

**Issue by sinper0212** [actframework/actframework#237]
```java
public static String formField(ActionContext ctx) {
        String paramName = ctx.config().csrfParamName();
        return S.newBuffer("<input type='hidden' name='").a(paramName).a("' value='").a(ctx.renderArg(paramName).toString()).a("'>").toString();
}
```

**Comment by greenlaw110** [comment]
@sinper0212 请贴出错误栈信息

**Comment by sinper0212** [comment]
![image](https://user-images.githubusercontent.com/4365564/27113823-f266f1a2-50f1-11e7-8887-e8520a7a82f8.png)

**Comment by greenlaw110** [comment]
无法重现,这个问题.我创建了这个演示程序: https://github.com/actframework/act-demo-apps/tree/master/csrf, 在其中有用到 `@_csrfField` 模板变量:
![image](https://user-images.githubusercontent.com/216930/34629818-b7cf384c-f2bd-11e7-9702-2dffd7de444c.png)

这是能够正常工作的:
![image](https://user-images.githubusercontent.com/216930/34629874-df80c6b2-f2bd-11e7-8e91-77a7c78f5cc1.png)
