### ISSUE TITLE
Act.start method overloads a single method signature with implied behaviours

### ISSUE THREAD

**Issue by CINJ** [actframework/actframework#257]
`Act.start(String, ...)` method signature overloads appName as well as ScanPackage and treats a name with . inside it as if it were a java package implicitly. Therefore, calling your app `my.app` even if the package is `com.my.app` would break the Java enhancement. 

Instead, there should be separate methods or method signatures on Act object which allow explicit calls:

1. set the app name when starting
2. override the scan package when starting
3. both setting the app name AND overriding the scan package when starting

**Comment by greenlaw110** [comment]
Fixed in 1.3.6 and 1.4.3
