### ISSUE TITLE
maven中央仓库没有1.4.4啊？

### ISSUE THREAD

**Issue by xiaojianyu315** [actframework/actframework#280]
如题

**Comment by greenlaw110** [comment]
有啊：
http://search.maven.org/#artifactdetails%7Corg.actframework%7Cact%7C1.4.4%7Cjar

**Comment by greenlaw110** [comment]
连阿里云上也都有了：
http://maven.aliyun.com/nexus/content/groups/public/org/actframework/act/1.4.4/
