### ISSUE TITLE
Support dynamic URL path variables

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#325]
Spring uses `@MatrixVariable` to support flexible URL path variable binding, e.g.

For given URL

```
http://localhost:8080/spring-mvc-java/companyEmployee/id=2;name=Xpto/employeeData/id=1;name=John;contactNumber=2200112334
```

The following code can binding the dynamic variables defined inside it:

```java
@RequestMapping(
 value = "/companyEmployee/{company}/employeeData/{employee}",
 method = RequestMethod.GET)
@ResponseBody
public ResponseEntity<Map<String, String>> getEmployeeDataFromCompany(
  @MatrixVariable(pathVar = "company") Map<String, String> company,
  @MatrixVariable(pathVar = "employee") Map<String, String> employee
) {
  ...
}
```

This request is to add the support to binding to dynamic variable pairs in URL path into ActFramework

**Comment by greenlaw110** [comment]
The proposed solution in Act:

Case 1

```java
@GetRequest("/companyEmployee/{company}/employeeData/{employee}")
public void companyEmployee(Map<String, String> company, Map<String, String> employee) {}
```

Case 2

```java
@GetRequest("/companyEmployee/{company}/employeeData/{employee}")
public void companyEmployee(Company company, Employee employee) {}
```

**Comment by CINJ** [comment]
This implicit solution works for non REST query strings just as well and does not need all the extra gunk used by spring. 

_Sent from my Xiaomi Redmi 3S using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by greenlaw110** [comment]
To be honest the URL messed up with query data looks a bit weird to me. Adding them into URL does **NOT** mean they are RESTful, and passing the data using query parameter does **NOT** mean it is not RESTful.

**Comment by greenlaw110** [comment]
The current solution goes case 1:

```java
@GetRequest("/companyEmployee/{company}/employeeData/{employee}")
public void companyEmployee(Map<String, String> company, Map<String, String> employee) {}
```

I think it goes too far to encode a full fleshed `POJO` into a URL part like `{company}` or `{employee}`.
