### ISSUE TITLE
Add support for webjars

### ISSUE THREAD

**Issue by dreamkidd** [actframework/actframework#331]
i add webjars to the classpath...
but i can't router static files which is in .jar file
hope can add support for webjars

**Comment by greenlaw110** [comment]
Now it can use webjars easily:

1. add webjars to your `pom.xml` file, e.g.

```xml
<dependency>
  <groupId>org.webjars</groupId>
  <artifactId>bootstrap</artifactId>
  <version>3.1.0</version>
</dependency>
```

2. In the html page refer to the webjar in the following way:

```html
<link type="text/css" rel="stylesheet" href="/webjars/bootstrap/3.1.0/css/bootstrap.css">
```
