### ISSUE TITLE
Export `ViewManager.getTemplate` API to application

### ISSUE THREAD

**Issue by d925529** [actframework/actframework#352]
1. 能够在应用程序中注入 `ViewManager`
2. 在 `ViewManager `上面加上一个` API`，传入模板路径，返回 `Template`

**Comment by greenlaw110** [comment]
Now it can do something like [this](https://github.com/actframework/actframework/blob/1.6/testapp/src/main/java/testapp/endpoint/ghissues/GH352.java):

```java
    @Before
    public void setupRenderArgs() {
        context.renderArg("who", "Act");
    }

    @GetAction("inline")
    public String testInline(ViewManager viewManager) {
        return viewManager.getTemplate("Hello @who").render(context);
    }

    @GetAction
    public String test(ViewManager viewManager) {
        return viewManager.getTemplate("/gh/352/test.html").render(context);
    }
```

Note the `@TemplateContext` annotation is not effective in the direct API call of `ViewManager.getTemplate(...)`.
