### ISSUE TITLE
官网下载的那个helloworld demo 1.4.13不能运行

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#395]
把原来的pom.xml的act版本改1.3.3改成1.4.13就不能运行了。我改了一些代码，但是报错的时候没有改几个代码，就是改了下包名之类的。报错在Act.start("App runing")这个入口函数。

1.

**Comment by greenlaw110** [comment]
可以运行啊:

![image](https://user-images.githubusercontent.com/216930/32320807-178d1bba-c013-11e7-95fb-85df10e0a0f3.png)
