### ISSUE TITLE
Support throttle control

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#435]
1. Throttle control on an action handler method

```java
@GetAction("foo")
@Throttled(4) // no more than 4 requests from the same ip 
public void foo() {
}
```

2. Throttle control on an route table entry

```
GET /foo resource[throttled]:/asset/foo.html
```

**Comment by CINJ** [comment]
Can we add SCALAR throttle control. This should support infinite requests from that IP, but for every request under TIMEOUT threshold it scales the respond-delay by the number of requests from the client IP? ie: DELAY = TIMEOUT ^ IP_REQUESTS_COUNT

Can we control TIMEOUT param on configuration? Currently - even with the IP request, it is unclear how to control the TIMEOUT value for blocking.

**Comment by greenlaw110** [comment]
Supported in act-1.6.0-RC3-SNAPSHOT. Test code

```java
    @GetAction("gh/435/2")
    @Throttled(value = 1, expireScale = ENABLED)
    public String test2() {
        return "GH435 - throttle control with expire scale";
    }
```

However it should be noted there will be small performance decrement enabled expire scale as it will request cache service twice. Not a big problem with single node but definitely needs attention when run the app in a multiple node configuration with distributed cache service.
