### ISSUE TITLE
Support using MACRO for URL path regex definition

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#438]
For a given URL path definition with regex included like

```
@GetAction("users/{username:[a-zA-Z][a-zA-Z_0-9]*}")
```

It would be nice to allow developer using macro to subsitude the regex part `[a-zA-Z][a-zA-Z_0-9]*`, and write something like:

```
@GetAction("users/{username:__USER_NAME__}")
```

The macro definition can be put into configuration file, something like:

```
route.regex.macro.__USER_NAME__=[a-zA-Z][a-zA-Z_0-9]*
```

This makes it easier for user to code the validation in URL paths, more importantly, it makes it much easier to update validation rules when needed.

**Comment by zhangsaizz** [comment]
so good!
