### ISSUE TITLE
POJO Binding failure

### ISSUE THREAD

**Issue by ttbadr** [actframework/actframework#446]
Sometimes we have strange POJO binding failure. 

Here is the binding type:

```java
public class DataTable {
    ...
    public int start;
    public int length;
    public Map<String, String> search;
    public List<Map<String, String>> columns;
}
```

Here is the action handler method:

```java
    @PostAction("list")
    public DataTable list(DataTable table, ...) {
        ...
        return orderService.list(table, searchParams);
    }
```

Here is the data to be bound:

![image](https://user-images.githubusercontent.com/216930/34666570-25ac3e3a-f4b9-11e7-9a1d-2f49eebc3327.png)

**Comment by greenlaw110** [comment]
The issue is caused by data:

![image](https://user-images.githubusercontent.com/216930/34666734-da6fa014-f4b9-11e7-922b-8390755a115c.png)

The data in red box doesn't fit the declared data type `List<Map<String, String>> columns`.

**Comment by greenlaw110** [comment]
@ttbadr thank you for contributing this issue, although it's not a direct ActFramework but, but during the investigating excerise we do identified a potential issue with Act, which is captured in #449
