### ISSUE TITLE
Support `X-Forwarded-For` to allow app get real remote ip when app is behind a reverse proxy

### ISSUE THREAD

**Issue by ttbadr** [actframework/actframework#454]
At the moment when we use nginx as reverse proxy we always get `127.0.0.1` when calling `H.Request.ip()`. It would be nice to resolve the remote ip from `X-Forwarded-For` header.

**Comment by greenlaw110** [comment]
@ttbadr this is a bug of actframework. Before this bug is fixed please apply the following workaround in your application:

```java
    @OnAppStart
    public void configXForwardedAllowed() {
        HttpConfig.setXForwardedAllowed("all");
    }
```
