### ISSUE TITLE
Turn off `@CacheFor ` on `dev` mode

### ISSUE THREAD

**Issue by d925529** [actframework/actframework#455]
It would nice to turn off `@CacheFor` on `dev` mode, or at least make it able to be turned off through configuration.

The main justification is we don't want to see cached content while template is refreshed.

**Comment by greenlaw110** [comment]
@d925529 我又仔细想了一下,觉得没有理由让 cacheFor 在开发模式下不起作用. 你觉得呢?

**Comment by greenlaw110** [comment]
Now we got new configuration `cacheFor.dev.enabled` with default value `false`, meaning `@CacheFor` is turned off by default on `dev` mode.

To turn on `@CacheFor` on `dev` mode, add the following configuration:

```
cacheFor.dev=true
```
