### ISSUE TITLE
`Act.cuid()` generates duplicate id randomly

### ISSUE THREAD

**Issue by d925529** [actframework/actframework#479]
两个方法：

`uuid` : 

```
    public Result save(@NotNull(message = "必须传递资源数据") @Valid FrContent frContent) {
         frContent.setFrconid(S.uuid());
         frContentMapper.insert(frContent);
    }
```

`cuid` 

```
    public Result save(@NotNull(message = "必须传递资源数据") @Valid FrContent frContent) {
         frContent.setFrconid(Act.cuid());
         frContentMapper.insert(frContent);
    }
```

测试之前数据库清空，使用`postman` `runner `功能每种连续调用。

1. 重复1000次，不会出现重复记录
2. 重复3000次，uuid失败0次，cuid失败510次
3. 重复6000次，uuid失败0次，cuid失败1070次

> 失败数据是分散在N次测试中的，中间会有间隔几次成功

![cuid](https://github.com/d925529/apidoc/blob/dev/doc/cuid.png?raw=true)

![uuid](https://github.com/d925529/apidoc/blob/dev/doc/uuid.png?raw=true)

**Comment by greenlaw110** [comment]
As we have discussed, this is caused by database configuration not supporting case sensitive id with `varchar` type. Not a problem of ActFramework.
