### ISSUE TITLE
`context.username()` returns `null` after upgrade act to 1.6.4

### ISSUE THREAD

**Issue by pcmanjack** [actframework/actframework#485]
Found on version: r1.6.4

The code to store username:

```java
session.put("username", userData.getUserName());
```

Then I use `context.username()` to fetch the username stored in session.

It works on r1.5.3, but doesn't work on r1.6.4

**Comment by greenlaw110** [comment]
@pcmanjack 

Please use `context.login(userData.getUserName())` to replace `session.put("username", userData.getUserName())` in your code. It will work in the act-1.6.4

However there is a bug in `AppConfig` that cause your working code broken. I will need to release a bug fix version for that.
