### ISSUE TITLE
1.6.4 比起 1.5.x 变慢

### ISSUE THREAD

**Issue by mailtous** [actframework/actframework#486]
1.6.4 比起 1.5.x 变慢1.6.4 比起 1.5.x 变慢
项目地址：https://github.com/mailtous/act-eagle-allone
![act1 6 4-start](https://user-images.githubusercontent.com/3850838/35421992-47eb945c-0281-11e8-8c6f-c359f1ba6a90.png)

**Comment by greenlaw110** [comment]
@mailtous 你能不能把能重现这个问题的项目打包发给我?

**Comment by greenlaw110** [comment]
reporter confirmed it's due to his environment as switching back to 1.5.x still takes the same amount of time to bootup
