### ISSUE TITLE
The content of big JSON response is not completed

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#487]
从MySQL数据库查询数据并返回，output不完整，outputStream才完整！

**这样写法的返回，浏览器还是Restful API客户端查看字符串都是正常的！ **
<img width="801" alt="qq20180127-170754 2x" src="https://user-images.githubusercontent.com/9036838/35470480-2d158890-0385-11e8-8725-5f12cf5a3e96.png">

**这样的写法返回，浏览器和Rest 客户端都不正常，浏览器转圈已经停止了，但是页面的内容不完整！**
<img width="742" alt="qq20180127-170847 2x" src="https://user-images.githubusercontent.com/9036838/35470498-81e30abe-0385-11e8-8b2f-4bfd3b519c7e.png">

不是数据查询出了问题，控制台打印是完整的字符串的 ，就是直接return 返回不正常！ 把数据的字段减少一点也是正常的，就是内容比较长就不行。

如果是HTTP传输协议的问题，同样的字符串结果，我测试了ThinkPHP返回是正常的。不知道在Act里面可以一般情况下返回完整的值而不超时或者断线吗

正常应该返回的字符串文件：
[https://github.com/jiankian/jiankian.github.io/blob/master/area.json](https://github.com/jiankian/jiankian.github.io/blob/master/area.json)

**Comment by greenlaw110** [comment]
@jiankian 你试试这个:

```java
@GetAction("area")
public Object index() {
    return areaDao.findAll();
}
```

**Comment by jiankian** [comment]
@greenlaw110 直接return dao.findAll()的话 页面打不开 无响应。dao.findAllList()的话返回的是指针地址，不是JSON字符串，JSON.toJSONString才返回json字符串，但是不完整

**Comment by greenlaw110** [comment]
> @greenlaw110 直接return dao.findAll()的话 页面打不开 无响应。dao.findAllList()的话返回的是指针地址，不是JSON字符串，JSON.toJSONString才返回json字符串，但是不完整

我测试了一下,没有问题呢? 你 checkout 这个项目运行下试试:

https://github.com/greenlaw110/act-projects/tree/master/gh487

**Comment by greenlaw110** [comment]
@jiankian 你在最新的 1.8.2-SNAPSHOT 上试试看，如果没问题就把这个 issue close 了吧
