### ISSUE TITLE
apidoc - issue with argument list

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#488]
我的子控制器继承父类控制器，apidoc里面会出来请求的参数列表。参数里面有父类的属性，如果我在父类定义了全局属性，那些api请求加入这些属性的参数是不是就会携带到我的接口里？

我的api请求时候，方法里会不会被带入的参数而把我父级的属性的值更改了，在我接下来方法中获取的值已经被方法里的参数一样被客户端的请求影响了。这样安全吗？我自己在客户端试了一下，传入apidoc那样的格式参数传参，倒是没有改变我api接口中的值

![qq20180128-015441](https://user-images.githubusercontent.com/9036838/35474885-80a91c5c-03cf-11e8-87f3-0d1b4def9e3b.png)
![qq20180128-015655](https://user-images.githubusercontent.com/9036838/35474886-811c0e60-03cf-11e8-8b36-63dacc333825.png)
![qq20180128-015745](https://user-images.githubusercontent.com/9036838/35474915-18e8a91a-03d0-11e8-949a-9dc5a22e66f2.png)
![qq20180128-015818](https://user-images.githubusercontent.com/9036838/35474930-57e7e7ac-03d0-11e8-8001-1704ecfa9dcd.png)

**Comment by greenlaw110** [comment]
@jiankian 
是的,你在父类中定义的 protected 的字段都是 subject to parameter binding 的. 如果你不希望这些字段被请求参数绑定,你需要在字段上面加上 `@act.inject.param.NoBind` 注解
