### ISSUE TITLE
Upgrade act 1.7.0,act-ebean2 1.4.0,Ebean model is not enhanced?

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#526]
search for bing.com, display all about Play Framework, how about actframework
<img width="1440" alt="qq20180221-051049 2x" src="https://user-images.githubusercontent.com/9036838/36449481-dd8d630c-16c5-11e8-8280-2411884b932e.png">

**Comment by jiankian** [comment]
in act 1.6.6:
 0 warings 0 errors

**Comment by greenlaw110** [comment]
@jiankian Cannot reproduce with [todo-ebean2](https://github.com/actframework/act-demo-apps/tree/master/todo-ebean2) sample project.

Can you please share your `pom.xml` file?

**Comment by jiankian** [comment]
[pom - 副本.xml.txt](https://github.com/actframework/actframework/files/1755921/pom.-.xml.txt)

**Comment by greenlaw110** [comment]
@jiankian is this actually a duplicate issue of #545 ?

**Comment by jiankian** [comment]
the newest 1.8.1 version is fixed
