### ISSUE TITLE
Different URL variable name caused duplicate routes not been reported

### ISSUE THREAD

**Issue by penguin290** [actframework/actframework#561]
Java source:

```java
    @GetAction("/a/{a}")
    public int home1(int a) {
        return a;
    }

    @GetAction("/a/{b}")
    public String home2(String b) {
        return b+1;
    }
```

Given the above code it shall report duplicate routes mapping error during app bootstrap, however it is not reported most probably caused by the different variable name `{a}` and `{b}`

**Comment by greenlaw110** [comment]
Fixed.

### Conflict sample one:

```
GET /a/{a}
GET /a/{b}
```

### Conflict sample two:

```
GET /a/{a}/abc
GET /a/{b}/abc
```

### Non conflict sample one:

```
GET /a/{<[a-z]+>id}
GET /a/{<[0-9]+>id}
```

### Non conflict sample two:

```
GET /foo/{name}-{qty}
GET /foo/{bar}
```
