### ISSUE TITLE
H.Request.ip() is null

### ISSUE THREAD

**Issue by dai875939260** [actframework/actframework#620]
H.Request.ip()获取到的是空值，使用context.req().ip()是正常的

**Comment by greenlaw110** [comment]
不能重现. 测试代码:

```java
    @GetAction("/test/gh620")
    public static String testGH620(H.Request req, ActionContext ctx) {
        return S.concat(req.ip(), " | ", ctx.req().ip());
    }
```

测试结果:

![image](https://user-images.githubusercontent.com/216930/38651169-14563086-3e43-11e8-9ad1-706062cefabf.png)

**Comment by dai875939260** [comment]
额，我的问题。
1.参数我这样写H.Request request，调试查看变量的是null，但是实际可以获取到ip。
2.如果参数H.Request req，调试变量是正常的。
![image](https://user-images.githubusercontent.com/6057326/38652102-0ef46a42-3e37-11e8-89ac-d2cd0c08fe84.png)

**Comment by greenlaw110** [comment]
@dai875939260 ip 字段是不会自动初始化的, 当你第一次调用 ip() 方法的时候才会检查是否为空, 并初始化
