### ISSUE TITLE
开发环境下session问题

### ISSUE THREAD

**Issue by dai875939260** [actframework/actframework#629]
开发环境下实时加载，session会失效有什么办法么？

**Comment by greenlaw110** [comment]
Session 是以 cookie 的形式存放在客户端的, 和服务器重启没有关系

**Comment by dai875939260** [comment]
可能我提问没到点上，例如
`ActionContext.current().session().cache("user", user)`
修改代码应用重新加载，`ActionContext.current().session().cache("user")`就为空了

**Comment by greenlaw110** [comment]
cache 肯定会消失的. 如果直接存 session 是不会有问题的. 我自己的做法是 session 存放 username, 如果需要从数据库中拿 User 对象
