### ISSUE TITLE
Dependency Injection with generic type

### ISSUE THREAD

**Issue by dai875939260** [actframework/actframework#637]
测试了一下，好像是不支持

**Comment by dai875939260** [comment]
```java
public class BaseService<T> {
    @Inject
    private BaseMapper<T> baseMapper;
}
```
```java
public interface ItemMapper extends BaseMapper<PactItem> {
}
```
```java
public class ItemService extends BaseService<ItemMapper>{
}
```
```java
org.osgl.exception.UnexpectedException: type not recognized: T
	at org.osgl.util.E.unexpected(E.java:179)
	at org.osgl.inject.BeanSpec.rawTypeOf(BeanSpec.java:837)
	at act.db.beetlsql.MapperLoader.load(MapperLoader.java:44)
	at act.db.beetlsql.MapperLoader.load(MapperLoader.java:37)
	at org.osgl.inject.Genie$5.get(Genie.java:925)
	at org.osgl.inject.Genie$6.get(Genie.java:967)
	at org.osgl.inject.Genie$FieldInjector.applyTo(Genie.java:472)
	at org.osgl.inject.Genie$8.get(Genie.java:1021)
	at org.osgl.inject.Genie$6.get(Genie.java:967)
```
好像api-doc也会因为范型报错，应该是beetlsql` PageQuery<T>`这个类

**Comment by greenlaw110** [comment]
控制器代码呢?

**Comment by dai875939260** [comment]
控制器就只注入了service 打开页面就报错了

**Comment by greenlaw110** [comment]
你的代码里面 `public class ItemService extends BaseService<ItemMapper>{}` 应该是 `public class ItemService extends BaseService<PackItem>{}` 才对, 不然类型匹配不上.

我做了一个实验项目, 代码在这里: https://github.com/greenlaw110/act-github-issues/tree/gh637

现在没有 `type not recognized: T` 的问题. 但是 `BaseService` 里面的 `mapper` 字段总是为 `null`. 我给 osgl-genie (act 使用的依赖注入库) 项目提了两个 issue:

* https://github.com/osglworks/java-di/issues/33
* https://github.com/osglworks/java-di/issues/34

必须等到这两个问题解决了你这种泛型注入才可以做

**Comment by dai875939260** [comment]
额，那个是我复制错了

**Comment by greenlaw110** [comment]
@dai875939260 osgl 那两个问题已经搞定, 你重新取一下 https://github.com/greenlaw110/act-github-issues/tree/gh637 试试. 我这边测试通过没问题

**Comment by dai875939260** [comment]
好像osgl-tool:1.10.1-SNAPSHOT下载不下来。。

**Comment by dai875939260** [comment]
![image](https://user-images.githubusercontent.com/6057326/39042166-c2e29714-44bc-11e8-909e-834af99af411.png)
依赖有问题么，osgl-tool没发现1.10.1-SNAPSHOT

**Comment by greenlaw110** [comment]
刚刚发布了，你再试试

**Comment by dai875939260** [comment]
可以了，非常感谢！
