### ISSUE TITLE
1.8.8快照版Excel导出无法使用了

### ISSUE THREAD

**Issue by dai875939260** [actframework/actframework#646]
现在都是404

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by greenlaw110** [comment]
Excel sample 项目的问题, 处于不知道的原因, 我误删掉了 src/main/resources/app.properties 文件. 里面应该有这样的配置:

```
content_suffix.aware=true
```

加上这个文件之后就可以了

**Comment by dai875939260** [comment]
好的。非常感谢！

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
