### ISSUE TITLE
osgl-tool 1.11.0-SNAPSHOT bring about  renderJSON Invalid

### ISSUE THREAD

**Issue by wenbin151** [actframework/actframework#655]
renderJson(daoCtlm1020app.findAll()); //Invalid
but:
renderJson("hello world");//it's work.

**Comment by dai875939260** [comment]
确实是。。。，@JsonView，  @ResponseContentType(H.MediaType.JSON)都失效了 @greenlaw110 能增加下单元测试再发布么

**Comment by greenlaw110** [comment]
@dai875939260 `renderJson` 失效的问题当时和 @wenbin151 联调的时候已经解决了, 是不是你的 SNAPSHOT 版本还没有刷新? 

因为是 SNAPSHOT 版本, 所以会有这样意料之外的情况. 给你添麻烦了. 以后我会更慎重的.

**Comment by dai875939260** [comment]
我这个好像还不是这个问题，我删除了本地的，因为依赖的还是1.10.1，不知道什么时候后端就没返回数据了。
```java
    @GetAction("userMenu")
    @JsonView
    public List<Menu> loadUserMenu() {
        return resourceService.findUserMenus();
    }
```
![image](https://user-images.githubusercontent.com/6057326/39745345-8ee19c1e-52d9-11e8-8070-2094a68d6350.png)
![image](https://user-images.githubusercontent.com/6057326/39745352-98499f22-52d9-11e8-81f3-eff5f3b243a7.png)

**Comment by greenlaw110** [comment]
@dai875939260 你另提一个 issue 吧, 把代码, act 的版本都列出来

**Comment by dai875939260** [comment]
ok

**Comment by greenlaw110** [comment]
This is caused by an issue in the conversion framework refactoring in osgl-tool-1.11.0-SNAPSHOT. That one has already been fixed in the formal release of osgl-tool-1.11.1
