### ISSUE TITLE
Beetl template render failure on PROD mode

### ISSUE THREAD

**Issue by dai875939260** [actframework/actframework#676]
版本：1.8.8.4
html页面没有任何返回，使用的是beetl
![image](https://user-images.githubusercontent.com/6057326/40981554-c50220da-690d-11e8-8cc6-9d4fcd198ac1.png)

正常返回200，但是没有返回任何内容。
===
每次升级都出问题，都没用下去的动力了😢

**Comment by greenlaw110** [comment]
我试了一下  https://github.com/actframework/act-demo-apps/tree/master/views, 使用 beetl 模板的时候是能够返回内容的呢?

act 版本:
![image](https://user-images.githubusercontent.com/216930/40998888-7cee3c72-694c-11e8-9641-a758fd90cb90.png)

测试页面:
![image](https://user-images.githubusercontent.com/216930/40998913-9b1b28cc-694c-11e8-90e8-b93e3dc75500.png)

**Comment by greenlaw110** [comment]
@dai875939260 真是不好意思, 项目大了,的确还是有些地方的 QA 做不到位. 还要靠你们一起来帮忙. 我能做到的就是收到问题反馈积极响应, 尽量缩短 bug 修复时间

**Comment by greenlaw110** [comment]
@dai875939260 我已经发现问题了. 正在修复 ...

**Comment by dai875939260** [comment]
我的问题是可以返回，但是浏览器状态一直在转
![image](https://user-images.githubusercontent.com/6057326/41009915-a69fad20-6966-11e8-973c-ad0f4dfbbe99.png)
控制台的没有返回任何html内容

**Comment by dai875939260** [comment]
有点失望。。 js加载不正常，之前提过一个缓存的bug。

左侧是assets下的文件，右侧是浏览器的加载的文件
===

![image](https://user-images.githubusercontent.com/6057326/41011300-d34e9590-696e-11e8-8141-abe6acc6c382.png)

**Comment by dai875939260** [comment]
部署在windows 2008下还是会卡住，在win10下部署，出现js加载异常（不是必现） 我没时间折腾这个东西了。。。
