### ISSUE TITLE
Headers not added to Result

### ISSUE THREAD

**Issue by samlotti2** [actframework/actframework#678]
When returning a response, I would like to add a header. So I did as follows.
```
return renderText(rslt).addHeader("header", "value");
```
however the header is not returned.
The code in Result.class contains the following method.
```
public Result addHeader(String name, String ... values) {
        H.Header header = this.headers.get(name);
        if (null == header) {
            header = new H.Header(name, values);
        } else {
            header = new H.Header(name, C.list(header.values()).append(C.listOf(values)));
        }
        return this;
    }
```
It appears the header is created but not added to the headers collection.

**Comment by greenlaw110** [comment]
Cuased by https://github.com/osglworks/java-mvc/issues/33
