### ISSUE TITLE
Broken links in read me file

### ISSUE THREAD

**Issue by htynkn** [actframework/actframework#73]
Here is a list for ACT Demo application in read me file, but those link are broken.

For example:
https://github.com/actframework/act-demo-apps/tree/master/fullstack-app/app-config
https://github.com/actframework/act-demo-apps/tree/master/fullstack-app/todo-morphia

**Comment by pengisgood** [comment]
The folder `fullstack-app` is obsolete obviously in the readme file here: 
https://github.com/actframework/act-demo-apps/tree/master/fullstack-app

I think these two links have been move to:
https://github.com/actframework/act-demo-apps/tree/master/config
https://github.com/actframework/act-demo-apps/tree/master/todo-morphia

So this issue can be closed IMHO.

**Comment by greenlaw110** [comment]
Thanks!
