### ISSUE TITLE
Java bean file loading not use default act FullStackAppBootstrapClassLoader cause Ebean failed

### ISSUE THREAD

**Issue by leeaee** [actframework/actframework#74]
@greenlaw110 
If java bean is in different POM module, the ACT framework start will not using FullStackAppBootstrapClassLoader.
This will caused the Ebean init failed.
The start project is [https://github.com/leeaee/bable/tree/snapshot](https://github.com/leeaee/bable/tree/snapshot). Running the nexus start app could see the issue.
The DB init script is under support/database.

**Comment by greenlaw110** [comment]
Use `act.modules` configuration to define submodules can solve this issue
