### ISSUE TITLE
Duplicate route mapping breaks the hot reloading and application state

### ISSUE THREAD

**Issue by CINJ** [actframework/actframework#81]
Adding two 'default' @GetAction handlers to a single class will cause ACT hot-reload to quit with other side-effects

Steps to reproduce:
1. run in dev mode with working code
2. add another @GetAction to a method in the same controller class
3. save file

When the file is saved, ACT hot-reload will throw an exception and exit.

Maybe there should be some kind of 'error state' with hot reload, so when you preview it says where the issue is so you can fix it and then it will try to leave that state when the files are changed again.

The other issue with the current situation is that the exit is not a clean exit. I have not been able to test this on other platforms, but on Windows when this state occurs, the underlying Java process never actually quits - it sits there holding on to the ports. 

Even stranger than this - if you change the ports in ACT configuration while this situation is happening, and try to restart ACT it STILL will not be able to access the ports since, it seems, the previous Java instance will not let the new Java instance access ANY ports! So, whatever happened to the Java process when the exception occurs is really serious.

**Comment by greenlaw110** [comment]
The issue is caused by reusing `App` instance, which has been destroyed already. However when the app is reload (due to code change etc) the destry state is still in `true`, and the following call destroy API will not effect. Thus the resources like CLI executor etc will never get released
