### ISSUE TITLE
JS can't access to response header fields in case of CORS requests

### ISSUE THREAD

**Issue by naixinxiaozi** [actframework/actframework#82]
In case of CORS requests, client app not be able to access other headers.  We need to set the Access-Control-Expose-Headers header on the server: 
`Access-Control-Expose-Headers: Access-Token, Uid`

Currently Act add Access-Control-Expose-Headers in OPTIONS response. But in fact, it it not enough. After my practice, the header must be added to POST,GET, or other responses when "cors=true".

https://github.com/mzabriskie/axios/issues/746

**Comment by greenlaw110** [comment]
check out https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS. Only response to OPTIONS request need to set teh `Access-Control-Expose-Headers`
