### ISSUE TITLE
可否把官网helloworld demo里的.project去掉

### ISSUE THREAD

**Issue by licardoY** [actframework/actframework#831]
下载这个项目:
![hwas](https://user-images.githubusercontent.com/20562449/45527939-bd512780-b810-11e8-9f9c-d4f837b5e90d.png)

解压:
![prj](https://user-images.githubusercontent.com/20562449/45527955-cd690700-b810-11e8-96ca-b96db532423f.png)

导入:
![pacc](https://user-images.githubusercontent.com/20562449/45527985-e376c780-b810-11e8-8fb4-c5c71e187743.png)

删掉.project就可以导入了

另外这里讨论要用英文吗还是都可以?

**Comment by greenlaw110** [comment]
官网的 demo 比较过时了. HelloWorld 程序的话, 依照 README 里面的方法用 maven archetype 创建一个吧. 目前暂时没有时间去照顾官网. 又空了要大修的

**Comment by licardoY** [comment]
好的,谢谢,act较小众网上搜到的资料很少,所以如果能有一份完善的文档就太棒了祝act越来越好
