### ISSUE TITLE
Provide a way to simple wrapped response data 

### ISSUE THREAD

**Issue by leeaee** [actframework/actframework#840]
Sometime, we will return the response data as
```json
{
  "username": "Genko Lee",
  "email": "leeaee@gmail.com"
}
```
In some scenario, we need response the data with some simple wrapped formata. 
For example:
```json
{
  "code": 0
  "data": {
    "username": "Genko Lee",
    "email": "leeaee@gmail.com"
  }
}
```
Could ACT provide a simple way just like a common interface in base class or some annonation to wrapped the response data?

**Comment by greenlaw110** [comment]
This is superseded by #835
