### ISSUE TITLE
ACT support read i18n properties outside JAR files

### ISSUE THREAD

**Issue by leeaee** [actframework/actframework#863]
Now, my i18n properties file placed in classes folder in release.
But the message could not read by ACT.
Can ACT support  read the i18n message files from external classes path?

**Comment by greenlaw110** [comment]
@leeaee is this only about validation message or general i18n messages?

**Comment by leeaee** [comment]
Its about general i18n messages.

**Comment by greenlaw110** [comment]
The issue is caused by message files not packed into the jar file
