### ISSUE TITLE
Act not return application/json as default when exception

### ISSUE THREAD

**Issue by leeaee** [actframework/actframework#870]
When throw exception, Act not return `application/json` as default content type.
Could there is an configuration parameter for global default content type?

**Comment by greenlaw110** [comment]
Now for any unknown `Accept` specification, it uses `application/json` as content-type for error response, make it align with the normal response.

By unknown, it means the `Accept` header of the request either does not exist or not anyone of the following content type:

* text/html
* text/csv
* application/json
* text/xml
