### ISSUE TITLE
ajax请求 @Valid 错误消息/http状态自定义

### ISSUE THREAD

**Issue by pcmanjack** [actframework/actframework#924]
框架会自动判断是否为ajax访问（主要通过header content-type X-Requested-With）
如果被判断为ajax请求。此时如果@Valid验证有错误。会直接返回400错误，和固定格式的json错误提示信息
但是有部分前端组件对错误信息的格式有固定要求。此时无法进行错误信息以及http状态码的自定义。
比如layui table 的错误信息返回格式要求为：
```
http status: 200
{
  "code": 1,
  "msg": "", 
  "count": 180, 
  "data": {
    "item": []
  }
}
```

**Comment by greenlaw110** [comment]
Duplicate to #922
