### ISSUE TITLE
renderJson date  yyyy-MM-dd HH:mm:ss

### ISSUE THREAD

**Issue by wd0472** [actframework/actframework#935]
renderJson返回数据日期格式yyyy-MM-dd HH:mm:ss或者允许添加日期格式参数

**Comment by greenlaw110** [comment]
The date format shall be defined in application properties, e.g.

```
fmt.date_time=yyyy-MM-dd HH:mm:ss
```

Please refer to https://github.com/actframework/actframework/tree/develop/testapps/GH935
