### ISSUE TITLE
Act-bean 1.7.4 cannot do ordering

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#942]
ebeanDAO需要加 setUseDocStore(false)才行，不加的话，不能使用.orderBy().desc("id")操作，提示maven缺少依赖 

![wx20181112-202629](https://user-images.githubusercontent.com/9036838/48347695-f5ae9e00-e6b9-11e8-8ec5-e1d8dab9fb5e.png)
加了依赖以后就不能启动  ActAct项目了
![wx20181112-202738](https://user-images.githubusercontent.com/9036838/48347715-05c67d80-e6ba-11e8-90e3-249b663f6226.png)
![wx20181112-202759](https://user-images.githubusercontent.com/9036838/48347720-09f29b00-e6ba-11e8-99f1-c945a925e42f.png)

**Comment by jiankian** [comment]
在之前一个不记得版本号的版本中，大概1.4.13版本里是可以正常运行，后来升级了 新版本这个要加setDocSource(false)才行，默认应该是ture

**Comment by greenlaw110** [comment]
<dependency>
      <groupId>org.avaje.ebeanorm</groupId>
      <artifactId>avaje-ebeanorm-elastic</artifactId>
      <version>1.3.1</version>
    </dependency>
```xml
    <dependency>
      <groupId>org.avaje.ebeanorm</groupId>
      <artifactId>avaje-ebeanorm-elastic</artifactId>
      <version>1.3.1</version>
    </dependency>
```

should be

```xml
    <dependency>
      <groupId>io.ebean</groupId>
      <artifactId>ebean-elastic</artifactId>
      <version>11.18.1</version>
    </dependency>
```
