### ISSUE TITLE
Issue with loading configuration into Map

### ISSUE THREAD

**Issue by donald2150** [actframework/actframework#946]
application properties

```properties
map.field.beginTime=2018
map.field.endTime=2019
```

Source code

```java
@Configuration("map.field")
private Map<String,String> map; 

public void test() {
    String s1 = map.get("begTime");
    String s2 = map.get("beg.time");
}
```

Running above test it found `s1` has no value, while `s2` has value, which is not expected.

**Comment by greenlaw110** [comment]
Cannot reproduce. Refer to https://github.com/actframework/actframework/blob/develop/testapps/GHIssues/src/main/java/ghissues/Gh946.java
