### ISSUE TITLE
WebSocket improvement about public and private channel/stream

### ISSUE THREAD

**Issue by ShizeZ** [actframework/actframework#951]
We might need support for WebSocket public/private channel/stream so that we can make sure WebSocket security.

**Comment by greenlaw110** [comment]
These concept has already been support:

* channel - supported via tag, any connection can subscript to a certain tag, and publisher can decide to publish the message to a tag, which will result in all connection subscribed get the message
* connection - it can send back message to the connection where the request message received
* user - it can send message to user account, any one logged in the account has a websocket connection will receive the message
